// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: rating/user/v1/user.proto
// Protobuf Java Version: 4.33.1

package com.rating.user.v1;

@com.google.protobuf.Generated
public interface GetUserRequestOrBuilder extends
    // @@protoc_insertion_point(interface_extends:rating.user.v1.GetUserRequest)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>int64 user_id = 1 [json_name = "userId"];</code>
   * @return The userId.
   */
  long getUserId();
}
