// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: rating/user/v1/user.proto
// Protobuf Java Version: 4.33.1

package com.rating.user.v1;

@com.google.protobuf.Generated
public interface ListUsersResponseOrBuilder extends
    // @@protoc_insertion_point(interface_extends:rating.user.v1.ListUsersResponse)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>repeated .rating.user.v1.User users = 1 [json_name = "users"];</code>
   */
  java.util.List<com.rating.user.v1.User> 
      getUsersList();
  /**
   * <code>repeated .rating.user.v1.User users = 1 [json_name = "users"];</code>
   */
  com.rating.user.v1.User getUsers(int index);
  /**
   * <code>repeated .rating.user.v1.User users = 1 [json_name = "users"];</code>
   */
  int getUsersCount();
  /**
   * <code>repeated .rating.user.v1.User users = 1 [json_name = "users"];</code>
   */
  java.util.List<? extends com.rating.user.v1.UserOrBuilder> 
      getUsersOrBuilderList();
  /**
   * <code>repeated .rating.user.v1.User users = 1 [json_name = "users"];</code>
   */
  com.rating.user.v1.UserOrBuilder getUsersOrBuilder(
      int index);
}
