// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: rating/user/v1/user.proto
// Protobuf Java Version: 4.33.1

package com.rating.user.v1;

@com.google.protobuf.Generated
public final class UserProto extends com.google.protobuf.GeneratedFile {
  private UserProto() {}
  static {
    com.google.protobuf.RuntimeVersion.validateProtobufGencodeVersion(
      com.google.protobuf.RuntimeVersion.RuntimeDomain.PUBLIC,
      /* major= */ 4,
      /* minor= */ 33,
      /* patch= */ 1,
      /* suffix= */ "",
      "UserProto");
  }
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_rating_user_v1_User_descriptor;
  static final 
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_rating_user_v1_User_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_rating_user_v1_CreateUserRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_rating_user_v1_CreateUserRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_rating_user_v1_CreateUserResponse_descriptor;
  static final 
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_rating_user_v1_CreateUserResponse_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_rating_user_v1_GetUserRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_rating_user_v1_GetUserRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_rating_user_v1_GetUserResponse_descriptor;
  static final 
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_rating_user_v1_GetUserResponse_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_rating_user_v1_ListUsersRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_rating_user_v1_ListUsersRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_rating_user_v1_ListUsersResponse_descriptor;
  static final 
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_rating_user_v1_ListUsersResponse_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\031rating/user/v1/user.proto\022\016rating.user" +
      ".v1\"\245\001\n\004User\022\035\n\nfirst_name\030\001 \001(\tR\tfirstN" +
      "ame\022\033\n\tlast_name\030\002 \001(\tR\010lastName\022\024\n\005emai" +
      "l\030\003 \001(\tR\005email\022\020\n\003age\030\004 \001(\rR\003age\022!\n\014phon" +
      "e_number\030\005 \001(\tR\013phoneNumber\022\026\n\006status\030\006 " +
      "\001(\tR\006status\"=\n\021CreateUserRequest\022(\n\004user" +
      "\030\001 \001(\0132\024.rating.user.v1.UserR\004user\">\n\022Cr" +
      "eateUserResponse\022(\n\004user\030\001 \001(\0132\024.rating." +
      "user.v1.UserR\004user\")\n\016GetUserRequest\022\027\n\007" +
      "user_id\030\001 \001(\003R\006userId\";\n\017GetUserResponse" +
      "\022(\n\004user\030\001 \001(\0132\024.rating.user.v1.UserR\004us" +
      "er\"\022\n\020ListUsersRequest\"?\n\021ListUsersRespo" +
      "nse\022*\n\005users\030\001 \003(\0132\024.rating.user.v1.User" +
      "R\005users2\200\002\n\013UserService\022S\n\nCreateUser\022!." +
      "rating.user.v1.CreateUserRequest\032\".ratin" +
      "g.user.v1.CreateUserResponse\022J\n\007GetUser\022" +
      "\036.rating.user.v1.GetUserRequest\032\037.rating" +
      ".user.v1.GetUserResponse\022P\n\tListUsers\022 ." +
      "rating.user.v1.ListUsersRequest\032!.rating" +
      ".user.v1.ListUsersResponseB\307\001\n\022com.ratin" +
      "g.user.v1B\tUserProtoP\001ZLgithub.com/dduzg" +
      "un-security/jug/jug-model/jug-model-go/r" +
      "ating/user/v1;userv1\242\002\003RUX\252\002\016Rating.User" +
      ".V1\312\002\016Rating\\User\\V1\342\002\032Rating\\User\\V1\\GP" +
      "BMetadata\352\002\020Rating::User::V1b\006proto3"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        });
    internal_static_rating_user_v1_User_descriptor =
      getDescriptor().getMessageType(0);
    internal_static_rating_user_v1_User_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_rating_user_v1_User_descriptor,
        new java.lang.String[] { "FirstName", "LastName", "Email", "Age", "PhoneNumber", "Status", });
    internal_static_rating_user_v1_CreateUserRequest_descriptor =
      getDescriptor().getMessageType(1);
    internal_static_rating_user_v1_CreateUserRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_rating_user_v1_CreateUserRequest_descriptor,
        new java.lang.String[] { "User", });
    internal_static_rating_user_v1_CreateUserResponse_descriptor =
      getDescriptor().getMessageType(2);
    internal_static_rating_user_v1_CreateUserResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_rating_user_v1_CreateUserResponse_descriptor,
        new java.lang.String[] { "User", });
    internal_static_rating_user_v1_GetUserRequest_descriptor =
      getDescriptor().getMessageType(3);
    internal_static_rating_user_v1_GetUserRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_rating_user_v1_GetUserRequest_descriptor,
        new java.lang.String[] { "UserId", });
    internal_static_rating_user_v1_GetUserResponse_descriptor =
      getDescriptor().getMessageType(4);
    internal_static_rating_user_v1_GetUserResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_rating_user_v1_GetUserResponse_descriptor,
        new java.lang.String[] { "User", });
    internal_static_rating_user_v1_ListUsersRequest_descriptor =
      getDescriptor().getMessageType(5);
    internal_static_rating_user_v1_ListUsersRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_rating_user_v1_ListUsersRequest_descriptor,
        new java.lang.String[] { });
    internal_static_rating_user_v1_ListUsersResponse_descriptor =
      getDescriptor().getMessageType(6);
    internal_static_rating_user_v1_ListUsersResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_rating_user_v1_ListUsersResponse_descriptor,
        new java.lang.String[] { "Users", });
    descriptor.resolveAllFeaturesImmutable();
  }

  // @@protoc_insertion_point(outer_class_scope)
}
