// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: rating/user/v1/user.proto
// Protobuf Java Version: 4.33.2

package com.rating.user.v1;

@com.google.protobuf.Generated
public final class UserProto extends com.google.protobuf.GeneratedFile {
  private UserProto() {}
  static {
    com.google.protobuf.RuntimeVersion.validateProtobufGencodeVersion(
      com.google.protobuf.RuntimeVersion.RuntimeDomain.PUBLIC,
      /* major= */ 4,
      /* minor= */ 33,
      /* patch= */ 2,
      /* suffix= */ "",
      "UserProto");
  }
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_rating_user_v1_User_descriptor;
  static final 
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_rating_user_v1_User_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_rating_user_v1_UserRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_rating_user_v1_UserRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_rating_user_v1_UserResponse_descriptor;
  static final 
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_rating_user_v1_UserResponse_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\031rating/user/v1/user.proto\022\016rating.user" +
      ".v1\"\245\001\n\004User\022\035\n\nfirst_name\030\001 \001(\tR\tfirstN" +
      "ame\022\033\n\tlast_name\030\002 \001(\tR\010lastName\022\024\n\005emai" +
      "l\030\003 \001(\tR\005email\022\020\n\003age\030\004 \001(\rR\003age\022!\n\014phon" +
      "e_number\030\005 \001(\tR\013phoneNumber\022\026\n\006status\030\006 " +
      "\001(\tR\006status\"7\n\013UserRequest\022(\n\004user\030\001 \001(\013" +
      "2\024.rating.user.v1.UserR\004user\"(\n\014UserResp" +
      "onse\022\030\n\007message\030\001 \001(\tR\007messageB\307\001\n\022com.r" +
      "ating.user.v1B\tUserProtoP\001ZLgithub.com/d" +
      "duzgun-security/jug/jug-model/jug-model-" +
      "go/rating/user/v1;userv1\242\002\003RUX\252\002\016Rating." +
      "User.V1\312\002\016Rating\\User\\V1\342\002\032Rating\\User\\V" +
      "1\\GPBMetadata\352\002\020Rating::User::V1b\006proto3"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        });
    internal_static_rating_user_v1_User_descriptor =
      getDescriptor().getMessageType(0);
    internal_static_rating_user_v1_User_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_rating_user_v1_User_descriptor,
        new java.lang.String[] { "FirstName", "LastName", "Email", "Age", "PhoneNumber", "Status", });
    internal_static_rating_user_v1_UserRequest_descriptor =
      getDescriptor().getMessageType(1);
    internal_static_rating_user_v1_UserRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_rating_user_v1_UserRequest_descriptor,
        new java.lang.String[] { "User", });
    internal_static_rating_user_v1_UserResponse_descriptor =
      getDescriptor().getMessageType(2);
    internal_static_rating_user_v1_UserResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_rating_user_v1_UserResponse_descriptor,
        new java.lang.String[] { "Message", });
    descriptor.resolveAllFeaturesImmutable();
  }

  // @@protoc_insertion_point(outer_class_scope)
}
