// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: rating/user/v1/user.proto

// Protobuf Java Version: 3.25.3
package com.rating.user.v1;

public interface UserRequestOrBuilder extends
    // @@protoc_insertion_point(interface_extends:rating.user.v1.UserRequest)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>.rating.user.v1.User user = 1 [json_name = "user"];</code>
   * @return Whether the user field is set.
   */
  boolean hasUser();
  /**
   * <code>.rating.user.v1.User user = 1 [json_name = "user"];</code>
   * @return The user.
   */
  com.rating.user.v1.User getUser();
  /**
   * <code>.rating.user.v1.User user = 1 [json_name = "user"];</code>
   */
  com.rating.user.v1.UserOrBuilder getUserOrBuilder();
}
