// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: rating/user/v1/user.proto
// Protobuf Java Version: 4.33.2

package com.rating.user.v1;

@com.google.protobuf.Generated
public final class UserOuterClass extends com.google.protobuf.GeneratedFile {
  private UserOuterClass() {}
  static {
    com.google.protobuf.RuntimeVersion.validateProtobufGencodeVersion(
      com.google.protobuf.RuntimeVersion.RuntimeDomain.PUBLIC,
      /* major= */ 4,
      /* minor= */ 33,
      /* patch= */ 2,
      /* suffix= */ "",
      "UserOuterClass");
  }
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_rating_user_v1_User_descriptor;
  static final 
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_rating_user_v1_User_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_rating_user_v1_UserRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_rating_user_v1_UserRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_rating_user_v1_UserResponse_descriptor;
  static final 
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_rating_user_v1_UserResponse_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\031rating/user/v1/user.proto\022\016rating.user" +
      ".v1\032\033buf/validate/validate.proto\"\244\003\n\004Use" +
      "r\022)\n\nfirst_name\030\001 \001(\tB\n\272H\007r\002\030@\310\001\001R\tfirst" +
      "Name\022\'\n\tlast_name\030\002 \001(\tB\n\272H\007r\002\030@\310\001\001R\010las" +
      "tName\022 \n\005email\030\003 \001(\tB\n\272H\007r\002`\001\310\001\001R\005email\022" +
      "\035\n\003age\030\004 \001(\rB\013\272H\010*\003\030\226\001\310\001\001R\003age\022=\n\014phone_" +
      "number\030\005 \001(\tB\032\272H\027r\0222\020^\\+\\d{1,3}\\d{9}$\310\001\001" +
      "R\013phoneNumber\022=\n\006status\030\006 \001(\tB%\272H\"r\0352\033^(" +
      "Active|Inactive|Premium)$\310\001\001R\006status:\210\001\272" +
      "H\204\001\032\201\001\n\035first_name_requires_last_name\0222l" +
      "ast_name must be present if first_name i" +
      "s present\032,!has(this.first_name) || has(" +
      "this.last_name)\"7\n\013UserRequest\022(\n\004user\030\001" +
      " \001(\0132\024.rating.user.v1.UserR\004user\"(\n\014User" +
      "Response\022\030\n\007message\030\001 \001(\tR\007messageBd\n\022co" +
      "m.rating.user.v1P\001ZLgithub.com/dduzgun-s" +
      "ecurity/jug/jug-model/jug-model-go/ratin" +
      "g/user/v1;userv1b\006proto3"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
          build.buf.validate.ValidateProto.getDescriptor(),
        });
    internal_static_rating_user_v1_User_descriptor =
      getDescriptor().getMessageType(0);
    internal_static_rating_user_v1_User_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_rating_user_v1_User_descriptor,
        new java.lang.String[] { "FirstName", "LastName", "Email", "Age", "PhoneNumber", "Status", });
    internal_static_rating_user_v1_UserRequest_descriptor =
      getDescriptor().getMessageType(1);
    internal_static_rating_user_v1_UserRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_rating_user_v1_UserRequest_descriptor,
        new java.lang.String[] { "User", });
    internal_static_rating_user_v1_UserResponse_descriptor =
      getDescriptor().getMessageType(2);
    internal_static_rating_user_v1_UserResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_rating_user_v1_UserResponse_descriptor,
        new java.lang.String[] { "Message", });
    descriptor.resolveAllFeaturesImmutable();
    build.buf.validate.ValidateProto.getDescriptor();
    com.google.protobuf.ExtensionRegistry registry =
        com.google.protobuf.ExtensionRegistry.newInstance();
    registry.add(build.buf.validate.ValidateProto.field);
    registry.add(build.buf.validate.ValidateProto.message);
    com.google.protobuf.Descriptors.FileDescriptor
        .internalUpdateFileDescriptor(descriptor, registry);
  }

  // @@protoc_insertion_point(outer_class_scope)
}
