// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: rating/user/v1/user.proto

// Protobuf Java Version: 3.25.3
package com.rating.user.v1;

public interface UserResponseOrBuilder extends
    // @@protoc_insertion_point(interface_extends:rating.user.v1.UserResponse)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string message = 1 [json_name = "message"];</code>
   * @return The message.
   */
  java.lang.String getMessage();
  /**
   * <code>string message = 1 [json_name = "message"];</code>
   * @return The bytes for message.
   */
  com.google.protobuf.ByteString
      getMessageBytes();
}
