// @generated by protoc-gen-es v2.10.1 with parameter "target=js,import_extension=js"
// @generated from file rating/user/v1/user.proto (package rating.user.v1, syntax proto3)
/* eslint-disable */

import { fileDesc, messageDesc } from "@bufbuild/protobuf/codegenv2";
import { file_buf_validate_validate } from "../../../buf/validate/validate_pb.js";

/**
 * Describes the file rating/user/v1/user.proto.
 */
export const file_rating_user_v1_user = /*@__PURE__*/
  fileDesc("ChlyYXRpbmcvdXNlci92MS91c2VyLnByb3RvEg5yYXRpbmcudXNlci52MSL4AgoEVXNlchIeCgpmaXJzdF9uYW1lGAEgASgJQgq6SAfIAQFyAhhAEh0KCWxhc3RfbmFtZRgCIAEoCUIKukgHyAEBcgIYQBIZCgVlbWFpbBgDIAEoCUIKukgHyAEBcgJgARIYCgNhZ2UYBCABKA1CC7pICMgBASoDGJYBEjoKDHBob25lX251bWJlchgFIAEoCUIkukghyAEBchwyGl4oXCtcZHsxLDN9W1xzLV0/KT9cZHsxMH0kEjUKBnN0YXR1cxgGIAEoCUIlukgiyAEBch0yG14oQWN0aXZlfEluYWN0aXZlfFByZW1pdW0pJDqIAbpIhAEagQEKHWZpcnN0X25hbWVfcmVxdWlyZXNfbGFzdF9uYW1lEjJsYXN0X25hbWUgbXVzdCBiZSBwcmVzZW50IGlmIGZpcnN0X25hbWUgaXMgcHJlc2VudBosIWhhcyh0aGlzLmZpcnN0X25hbWUpIHx8IGhhcyh0aGlzLmxhc3RfbmFtZSkiMQoLVXNlclJlcXVlc3QSIgoEdXNlchgBIAEoCzIULnJhdGluZy51c2VyLnYxLlVzZXIiHwoMVXNlclJlc3BvbnNlEg8KB21lc3NhZ2UYASABKAlCxwEKEmNvbS5yYXRpbmcudXNlci52MUIJVXNlclByb3RvUAFaTGdpdGh1Yi5jb20vZGR1emd1bi1zZWN1cml0eS9qdWcvanVnLW1vZGVsL2p1Zy1tb2RlbC1nby9yYXRpbmcvdXNlci92MTt1c2VydjGiAgNSVViqAg5SYXRpbmcuVXNlci5WMcoCDlJhdGluZ1xVc2VyXFYx4gIaUmF0aW5nXFVzZXJcVjFcR1BCTWV0YWRhdGHqAhBSYXRpbmc6OlVzZXI6OlYxYgZwcm90bzM", [file_buf_validate_validate]);

/**
 * Describes the message rating.user.v1.User.
 * Use `create(UserSchema)` to create a new message.
 */
export const UserSchema = /*@__PURE__*/
  messageDesc(file_rating_user_v1_user, 0);

/**
 * Describes the message rating.user.v1.UserRequest.
 * Use `create(UserRequestSchema)` to create a new message.
 */
export const UserRequestSchema = /*@__PURE__*/
  messageDesc(file_rating_user_v1_user, 1);

/**
 * Describes the message rating.user.v1.UserResponse.
 * Use `create(UserResponseSchema)` to create a new message.
 */
export const UserResponseSchema = /*@__PURE__*/
  messageDesc(file_rating_user_v1_user, 2);

