// @generated by protoc-gen-es v2.10.1 with parameter "target=js,import_extension=js"
// @generated from file rating/user/v1/user.proto (package rating.user.v1, syntax proto3)
/* eslint-disable */

import { fileDesc, messageDesc } from "@bufbuild/protobuf/codegenv2";
import { file_buf_validate_validate } from "../../../buf/validate/validate_pb.js";

/**
 * Describes the file rating/user/v1/user.proto.
 */
export const file_rating_user_v1_user = /*@__PURE__*/
  fileDesc("ChlyYXRpbmcvdXNlci92MS91c2VyLnByb3RvEg5yYXRpbmcudXNlci52MSLuAgoEVXNlchIeCgpmaXJzdF9uYW1lGAEgASgJQgq6SAfIAQFyAhhAEh0KCWxhc3RfbmFtZRgCIAEoCUIKukgHyAEBcgIYQBIZCgVlbWFpbBgDIAEoCUIKukgHyAEBcgJgARIYCgNhZ2UYBCABKA1CC7pICMgBASoDGJYBEjAKDHBob25lX251bWJlchgFIAEoCUIaukgXyAEBchIyEF5cK1xkezEsM31cZHs5fSQSNQoGc3RhdHVzGAYgASgJQiW6SCLIAQFyHTIbXihBY3RpdmV8SW5hY3RpdmV8UHJlbWl1bSkkOogBukiEARqBAQodZmlyc3RfbmFtZV9yZXF1aXJlc19sYXN0X25hbWUSMmxhc3RfbmFtZSBtdXN0IGJlIHByZXNlbnQgaWYgZmlyc3RfbmFtZSBpcyBwcmVzZW50GiwhaGFzKHRoaXMuZmlyc3RfbmFtZSkgfHwgaGFzKHRoaXMubGFzdF9uYW1lKSIxCgtVc2VyUmVxdWVzdBIiCgR1c2VyGAEgASgLMhQucmF0aW5nLnVzZXIudjEuVXNlciIfCgxVc2VyUmVzcG9uc2USDwoHbWVzc2FnZRgBIAEoCULHAQoSY29tLnJhdGluZy51c2VyLnYxQglVc2VyUHJvdG9QAVpMZ2l0aHViLmNvbS9kZHV6Z3VuLXNlY3VyaXR5L2p1Zy9qdWctbW9kZWwvanVnLW1vZGVsLWdvL3JhdGluZy91c2VyL3YxO3VzZXJ2MaICA1JVWKoCDlJhdGluZy5Vc2VyLlYxygIOUmF0aW5nXFVzZXJcVjHiAhpSYXRpbmdcVXNlclxWMVxHUEJNZXRhZGF0YeoCEFJhdGluZzo6VXNlcjo6VjFiBnByb3RvMw", [file_buf_validate_validate]);

/**
 * Describes the message rating.user.v1.User.
 * Use `create(UserSchema)` to create a new message.
 */
export const UserSchema = /*@__PURE__*/
  messageDesc(file_rating_user_v1_user, 0);

/**
 * Describes the message rating.user.v1.UserRequest.
 * Use `create(UserRequestSchema)` to create a new message.
 */
export const UserRequestSchema = /*@__PURE__*/
  messageDesc(file_rating_user_v1_user, 1);

/**
 * Describes the message rating.user.v1.UserResponse.
 * Use `create(UserResponseSchema)` to create a new message.
 */
export const UserResponseSchema = /*@__PURE__*/
  messageDesc(file_rating_user_v1_user, 2);

