// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.10
// 	protoc        (unknown)
// source: rating/consent/v1/consent.proto

package consentv1

import (
	_ "buf.build/gen/go/bufbuild/protovalidate/protocolbuffers/go/buf/validate"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Consent struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Email         string                 `protobuf:"bytes,1,opt,name=email,proto3" json:"email,omitempty"`
	Consent       bool                   `protobuf:"varint,2,opt,name=consent,proto3" json:"consent,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Consent) Reset() {
	*x = Consent{}
	mi := &file_rating_consent_v1_consent_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Consent) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Consent) ProtoMessage() {}

func (x *Consent) ProtoReflect() protoreflect.Message {
	mi := &file_rating_consent_v1_consent_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Consent.ProtoReflect.Descriptor instead.
func (*Consent) Descriptor() ([]byte, []int) {
	return file_rating_consent_v1_consent_proto_rawDescGZIP(), []int{0}
}

func (x *Consent) GetEmail() string {
	if x != nil {
		return x.Email
	}
	return ""
}

func (x *Consent) GetConsent() bool {
	if x != nil {
		return x.Consent
	}
	return false
}

type ConsentRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Consent       *Consent               `protobuf:"bytes,1,opt,name=consent,proto3" json:"consent,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ConsentRequest) Reset() {
	*x = ConsentRequest{}
	mi := &file_rating_consent_v1_consent_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ConsentRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ConsentRequest) ProtoMessage() {}

func (x *ConsentRequest) ProtoReflect() protoreflect.Message {
	mi := &file_rating_consent_v1_consent_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ConsentRequest.ProtoReflect.Descriptor instead.
func (*ConsentRequest) Descriptor() ([]byte, []int) {
	return file_rating_consent_v1_consent_proto_rawDescGZIP(), []int{1}
}

func (x *ConsentRequest) GetConsent() *Consent {
	if x != nil {
		return x.Consent
	}
	return nil
}

type ConsentResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Message       string                 `protobuf:"bytes,1,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ConsentResponse) Reset() {
	*x = ConsentResponse{}
	mi := &file_rating_consent_v1_consent_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ConsentResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ConsentResponse) ProtoMessage() {}

func (x *ConsentResponse) ProtoReflect() protoreflect.Message {
	mi := &file_rating_consent_v1_consent_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ConsentResponse.ProtoReflect.Descriptor instead.
func (*ConsentResponse) Descriptor() ([]byte, []int) {
	return file_rating_consent_v1_consent_proto_rawDescGZIP(), []int{2}
}

func (x *ConsentResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

var File_rating_consent_v1_consent_proto protoreflect.FileDescriptor

const file_rating_consent_v1_consent_proto_rawDesc = "" +
	"\n" +
	"\x1frating/consent/v1/consent.proto\x12\x11rating.consent.v1\x1a\x1bbuf/validate/validate.proto\"Q\n" +
	"\aConsent\x12 \n" +
	"\x05email\x18\x01 \x01(\tB\n" +
	"\xbaH\a\xc8\x01\x01r\x02`\x01R\x05email\x12$\n" +
	"\aconsent\x18\x02 \x01(\bB\n" +
	"\xbaH\a\xc8\x01\x01j\x02\b\x01R\aconsent\"F\n" +
	"\x0eConsentRequest\x124\n" +
	"\aconsent\x18\x01 \x01(\v2\x1a.rating.consent.v1.ConsentR\aconsent\"+\n" +
	"\x0fConsentResponse\x12\x18\n" +
	"\amessage\x18\x01 \x01(\tR\amessageB\xdf\x01\n" +
	"\x15com.rating.consent.v1B\fConsentProtoP\x01ZRgithub.com/dduzgun-security/jug/jug-model/jug-model-go/rating/consent/v1;consentv1\xa2\x02\x03RCX\xaa\x02\x11Rating.Consent.V1\xca\x02\x11Rating\\Consent\\V1\xe2\x02\x1dRating\\Consent\\V1\\GPBMetadata\xea\x02\x13Rating::Consent::V1b\x06proto3"

var (
	file_rating_consent_v1_consent_proto_rawDescOnce sync.Once
	file_rating_consent_v1_consent_proto_rawDescData []byte
)

func file_rating_consent_v1_consent_proto_rawDescGZIP() []byte {
	file_rating_consent_v1_consent_proto_rawDescOnce.Do(func() {
		file_rating_consent_v1_consent_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_rating_consent_v1_consent_proto_rawDesc), len(file_rating_consent_v1_consent_proto_rawDesc)))
	})
	return file_rating_consent_v1_consent_proto_rawDescData
}

var file_rating_consent_v1_consent_proto_msgTypes = make([]protoimpl.MessageInfo, 3)
var file_rating_consent_v1_consent_proto_goTypes = []any{
	(*Consent)(nil),         // 0: rating.consent.v1.Consent
	(*ConsentRequest)(nil),  // 1: rating.consent.v1.ConsentRequest
	(*ConsentResponse)(nil), // 2: rating.consent.v1.ConsentResponse
}
var file_rating_consent_v1_consent_proto_depIdxs = []int32{
	0, // 0: rating.consent.v1.ConsentRequest.consent:type_name -> rating.consent.v1.Consent
	1, // [1:1] is the sub-list for method output_type
	1, // [1:1] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_rating_consent_v1_consent_proto_init() }
func file_rating_consent_v1_consent_proto_init() {
	if File_rating_consent_v1_consent_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_rating_consent_v1_consent_proto_rawDesc), len(file_rating_consent_v1_consent_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   3,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_rating_consent_v1_consent_proto_goTypes,
		DependencyIndexes: file_rating_consent_v1_consent_proto_depIdxs,
		MessageInfos:      file_rating_consent_v1_consent_proto_msgTypes,
	}.Build()
	File_rating_consent_v1_consent_proto = out.File
	file_rating_consent_v1_consent_proto_goTypes = nil
	file_rating_consent_v1_consent_proto_depIdxs = nil
}
