// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.10
// 	protoc        (unknown)
// source: rating/user/v1/user.proto

package userv1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type User struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	FirstName     string                 `protobuf:"bytes,1,opt,name=first_name,json=firstName,proto3" json:"first_name,omitempty"`
	LastName      string                 `protobuf:"bytes,2,opt,name=last_name,json=lastName,proto3" json:"last_name,omitempty"`
	Email         string                 `protobuf:"bytes,3,opt,name=email,proto3" json:"email,omitempty"`
	Age           uint32                 `protobuf:"varint,4,opt,name=age,proto3" json:"age,omitempty"`
	PhoneNumber   string                 `protobuf:"bytes,5,opt,name=phone_number,json=phoneNumber,proto3" json:"phone_number,omitempty"`
	Status        string                 `protobuf:"bytes,6,opt,name=status,proto3" json:"status,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *User) Reset() {
	*x = User{}
	mi := &file_rating_user_v1_user_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *User) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*User) ProtoMessage() {}

func (x *User) ProtoReflect() protoreflect.Message {
	mi := &file_rating_user_v1_user_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use User.ProtoReflect.Descriptor instead.
func (*User) Descriptor() ([]byte, []int) {
	return file_rating_user_v1_user_proto_rawDescGZIP(), []int{0}
}

func (x *User) GetFirstName() string {
	if x != nil {
		return x.FirstName
	}
	return ""
}

func (x *User) GetLastName() string {
	if x != nil {
		return x.LastName
	}
	return ""
}

func (x *User) GetEmail() string {
	if x != nil {
		return x.Email
	}
	return ""
}

func (x *User) GetAge() uint32 {
	if x != nil {
		return x.Age
	}
	return 0
}

func (x *User) GetPhoneNumber() string {
	if x != nil {
		return x.PhoneNumber
	}
	return ""
}

func (x *User) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

var File_rating_user_v1_user_proto protoreflect.FileDescriptor

const file_rating_user_v1_user_proto_rawDesc = "" +
	"\n" +
	"\x19rating/user/v1/user.proto\x12\x0erating.user.v1\"\xa5\x01\n" +
	"\x04User\x12\x1d\n" +
	"\n" +
	"first_name\x18\x01 \x01(\tR\tfirstName\x12\x1b\n" +
	"\tlast_name\x18\x02 \x01(\tR\blastName\x12\x14\n" +
	"\x05email\x18\x03 \x01(\tR\x05email\x12\x10\n" +
	"\x03age\x18\x04 \x01(\rR\x03age\x12!\n" +
	"\fphone_number\x18\x05 \x01(\tR\vphoneNumber\x12\x16\n" +
	"\x06status\x18\x06 \x01(\tR\x06statusB\xc7\x01\n" +
	"\x12com.rating.user.v1B\tUserProtoP\x01ZLgithub.com/dduzgun-security/jug/jug-model/jug-model-go/rating/user/v1;userv1\xa2\x02\x03RUX\xaa\x02\x0eRating.User.V1\xca\x02\x0eRating\\User\\V1\xe2\x02\x1aRating\\User\\V1\\GPBMetadata\xea\x02\x10Rating::User::V1b\x06proto3"

var (
	file_rating_user_v1_user_proto_rawDescOnce sync.Once
	file_rating_user_v1_user_proto_rawDescData []byte
)

func file_rating_user_v1_user_proto_rawDescGZIP() []byte {
	file_rating_user_v1_user_proto_rawDescOnce.Do(func() {
		file_rating_user_v1_user_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_rating_user_v1_user_proto_rawDesc), len(file_rating_user_v1_user_proto_rawDesc)))
	})
	return file_rating_user_v1_user_proto_rawDescData
}

var file_rating_user_v1_user_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_rating_user_v1_user_proto_goTypes = []any{
	(*User)(nil), // 0: rating.user.v1.User
}
var file_rating_user_v1_user_proto_depIdxs = []int32{
	0, // [0:0] is the sub-list for method output_type
	0, // [0:0] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_rating_user_v1_user_proto_init() }
func file_rating_user_v1_user_proto_init() {
	if File_rating_user_v1_user_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_rating_user_v1_user_proto_rawDesc), len(file_rating_user_v1_user_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   1,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_rating_user_v1_user_proto_goTypes,
		DependencyIndexes: file_rating_user_v1_user_proto_depIdxs,
		MessageInfos:      file_rating_user_v1_user_proto_msgTypes,
	}.Build()
	File_rating_user_v1_user_proto = out.File
	file_rating_user_v1_user_proto_goTypes = nil
	file_rating_user_v1_user_proto_depIdxs = nil
}
