// @generated by protoc-gen-es v2.10.1 with parameter "target=ts"
// @generated from file rating/consent/v1/consent.proto (package rating.consent.v1, syntax proto3)
/* eslint-disable */

import type { GenFile, GenMessage } from "@bufbuild/protobuf/codegenv2";
import { fileDesc, messageDesc } from "@bufbuild/protobuf/codegenv2";
import type { Message } from "@bufbuild/protobuf";

/**
 * Describes the file rating/consent/v1/consent.proto.
 */
export const file_rating_consent_v1_consent: GenFile = /*@__PURE__*/
  fileDesc("Ch9yYXRpbmcvY29uc2VudC92MS9jb25zZW50LnByb3RvEhFyYXRpbmcuY29uc2VudC52MSIpCgdDb25zZW50Eg0KBWVtYWlsGAEgASgJEg8KB2NvbnNlbnQYAiABKAgiPQoOQ29uc2VudFJlcXVlc3QSKwoHY29uc2VudBgBIAEoCzIaLnJhdGluZy5jb25zZW50LnYxLkNvbnNlbnQiIgoPQ29uc2VudFJlc3BvbnNlEg8KB21lc3NhZ2UYASABKAlC3wEKFWNvbS5yYXRpbmcuY29uc2VudC52MUIMQ29uc2VudFByb3RvUAFaUmdpdGh1Yi5jb20vZGR1emd1bi1zZWN1cml0eS9qdWcvanVnLW1vZGVsL2p1Zy1tb2RlbC1nby9yYXRpbmcvY29uc2VudC92MTtjb25zZW50djGiAgNSQ1iqAhFSYXRpbmcuQ29uc2VudC5WMcoCEVJhdGluZ1xDb25zZW50XFYx4gIdUmF0aW5nXENvbnNlbnRcVjFcR1BCTWV0YWRhdGHqAhNSYXRpbmc6OkNvbnNlbnQ6OlYxYgZwcm90bzM");

/**
 * @generated from message rating.consent.v1.Consent
 */
export type Consent = Message<"rating.consent.v1.Consent"> & {
  /**
   * @generated from field: string email = 1;
   */
  email: string;

  /**
   * @generated from field: bool consent = 2;
   */
  consent: boolean;
};

/**
 * Describes the message rating.consent.v1.Consent.
 * Use `create(ConsentSchema)` to create a new message.
 */
export const ConsentSchema: GenMessage<Consent> = /*@__PURE__*/
  messageDesc(file_rating_consent_v1_consent, 0);

/**
 * @generated from message rating.consent.v1.ConsentRequest
 */
export type ConsentRequest = Message<"rating.consent.v1.ConsentRequest"> & {
  /**
   * @generated from field: rating.consent.v1.Consent consent = 1;
   */
  consent?: Consent;
};

/**
 * Describes the message rating.consent.v1.ConsentRequest.
 * Use `create(ConsentRequestSchema)` to create a new message.
 */
export const ConsentRequestSchema: GenMessage<ConsentRequest> = /*@__PURE__*/
  messageDesc(file_rating_consent_v1_consent, 1);

/**
 * @generated from message rating.consent.v1.ConsentResponse
 */
export type ConsentResponse = Message<"rating.consent.v1.ConsentResponse"> & {
  /**
   * @generated from field: string message = 1;
   */
  message: string;
};

/**
 * Describes the message rating.consent.v1.ConsentResponse.
 * Use `create(ConsentResponseSchema)` to create a new message.
 */
export const ConsentResponseSchema: GenMessage<ConsentResponse> = /*@__PURE__*/
  messageDesc(file_rating_consent_v1_consent, 2);

