// @generated by protoc-gen-es v2.10.1 with parameter "target=js,import_extension=js"
// @generated from file rating/consent/v1/consent.proto (package rating.consent.v1, syntax proto3)
/* eslint-disable */

import { fileDesc, messageDesc } from "@bufbuild/protobuf/codegenv2";
import { file_buf_validate_validate } from "../../../buf/validate/validate_pb.js";

/**
 * Describes the file rating/consent/v1/consent.proto.
 */
export const file_rating_consent_v1_consent = /*@__PURE__*/
  fileDesc("Ch9yYXRpbmcvY29uc2VudC92MS9jb25zZW50LnByb3RvEhFyYXRpbmcuY29uc2VudC52MSJBCgdDb25zZW50EhkKBWVtYWlsGAEgASgJQgq6SAfIAQFyAmABEhsKB2NvbnNlbnQYAiABKAhCCrpIB8gBAWoCCAEiPQoOQ29uc2VudFJlcXVlc3QSKwoHY29uc2VudBgBIAEoCzIaLnJhdGluZy5jb25zZW50LnYxLkNvbnNlbnQiIgoPQ29uc2VudFJlc3BvbnNlEg8KB21lc3NhZ2UYASABKAlC3wEKFWNvbS5yYXRpbmcuY29uc2VudC52MUIMQ29uc2VudFByb3RvUAFaUmdpdGh1Yi5jb20vZGR1emd1bi1zZWN1cml0eS9qdWcvanVnLW1vZGVsL2p1Zy1tb2RlbC1nby9yYXRpbmcvY29uc2VudC92MTtjb25zZW50djGiAgNSQ1iqAhFSYXRpbmcuQ29uc2VudC5WMcoCEVJhdGluZ1xDb25zZW50XFYx4gIdUmF0aW5nXENvbnNlbnRcVjFcR1BCTWV0YWRhdGHqAhNSYXRpbmc6OkNvbnNlbnQ6OlYxYgZwcm90bzM", [file_buf_validate_validate]);

/**
 * Describes the message rating.consent.v1.Consent.
 * Use `create(ConsentSchema)` to create a new message.
 */
export const ConsentSchema = /*@__PURE__*/
  messageDesc(file_rating_consent_v1_consent, 0);

/**
 * Describes the message rating.consent.v1.ConsentRequest.
 * Use `create(ConsentRequestSchema)` to create a new message.
 */
export const ConsentRequestSchema = /*@__PURE__*/
  messageDesc(file_rating_consent_v1_consent, 1);

/**
 * Describes the message rating.consent.v1.ConsentResponse.
 * Use `create(ConsentResponseSchema)` to create a new message.
 */
export const ConsentResponseSchema = /*@__PURE__*/
  messageDesc(file_rating_consent_v1_consent, 2);

