// @generated by protoc-gen-es v2.10.1 with parameter "target=js,import_extension=js"
// @generated from file rating/poutine/v1/poutine.proto (package rating.poutine.v1, syntax proto3)
/* eslint-disable */

import { fileDesc, messageDesc } from "@bufbuild/protobuf/codegenv2";

/**
 * Describes the file rating/poutine/v1/poutine.proto.
 */
export const file_rating_poutine_v1_poutine = /*@__PURE__*/
  fileDesc("Ch9yYXRpbmcvcG91dGluZS92MS9wb3V0aW5lLnByb3RvEhFyYXRpbmcucG91dGluZS52MSKMAQoHUG91dGluZRISCgpyZXN0YXVyYW50GAEgASgJEhoKEmNoZWVzZV9zcXVlYWtpbmVzcxgCIAEoDRIXCg9ncmF2eV90aGlja25lc3MYAyABKA0SGAoQZnJpZXNfY3Jpc3BpbmVzcxgEIAEoDRIMCgRzaXplGAUgASgJEhAKCGNvbW1lbnRzGAYgASgJIj0KDlBvdXRpbmVSZXF1ZXN0EisKB3BvdXRpbmUYASABKAsyGi5yYXRpbmcucG91dGluZS52MS5Qb3V0aW5lIjkKD1BvdXRpbmVSZXNwb25zZRIPCgdtZXNzYWdlGAEgASgJEhUKDWF2ZXJhZ2Vfc2NvcmUYAiABKAJC3wEKFWNvbS5yYXRpbmcucG91dGluZS52MUIMUG91dGluZVByb3RvUAFaUmdpdGh1Yi5jb20vZGR1emd1bi1zZWN1cml0eS9qdWcvanVnLW1vZGVsL2p1Zy1tb2RlbC1nby9yYXRpbmcvcG91dGluZS92MTtwb3V0aW5ldjGiAgNSUFiqAhFSYXRpbmcuUG91dGluZS5WMcoCEVJhdGluZ1xQb3V0aW5lXFYx4gIdUmF0aW5nXFBvdXRpbmVcVjFcR1BCTWV0YWRhdGHqAhNSYXRpbmc6OlBvdXRpbmU6OlYxYgZwcm90bzM");

/**
 * Describes the message rating.poutine.v1.Poutine.
 * Use `create(PoutineSchema)` to create a new message.
 */
export const PoutineSchema = /*@__PURE__*/
  messageDesc(file_rating_poutine_v1_poutine, 0);

/**
 * Describes the message rating.poutine.v1.PoutineRequest.
 * Use `create(PoutineRequestSchema)` to create a new message.
 */
export const PoutineRequestSchema = /*@__PURE__*/
  messageDesc(file_rating_poutine_v1_poutine, 1);

/**
 * Describes the message rating.poutine.v1.PoutineResponse.
 * Use `create(PoutineResponseSchema)` to create a new message.
 */
export const PoutineResponseSchema = /*@__PURE__*/
  messageDesc(file_rating_poutine_v1_poutine, 2);

