// @generated by protoc-gen-es v2.10.1 with parameter "target=ts"
// @generated from file rating/poutine/v1/poutine.proto (package rating.poutine.v1, syntax proto3)
/* eslint-disable */

import type { GenFile, GenMessage } from "@bufbuild/protobuf/codegenv2";
import { fileDesc, messageDesc } from "@bufbuild/protobuf/codegenv2";
import type { Message } from "@bufbuild/protobuf";

/**
 * Describes the file rating/poutine/v1/poutine.proto.
 */
export const file_rating_poutine_v1_poutine: GenFile = /*@__PURE__*/
  fileDesc("Ch9yYXRpbmcvcG91dGluZS92MS9wb3V0aW5lLnByb3RvEhFyYXRpbmcucG91dGluZS52MSKMAQoHUG91dGluZRISCgpyZXN0YXVyYW50GAEgASgJEhoKEmNoZWVzZV9zcXVlYWtpbmVzcxgCIAEoDRIXCg9ncmF2eV90aGlja25lc3MYAyABKA0SGAoQZnJpZXNfY3Jpc3BpbmVzcxgEIAEoDRIMCgRzaXplGAUgASgJEhAKCGNvbW1lbnRzGAYgASgJIj0KDlBvdXRpbmVSZXF1ZXN0EisKB3BvdXRpbmUYASABKAsyGi5yYXRpbmcucG91dGluZS52MS5Qb3V0aW5lIjkKD1BvdXRpbmVSZXNwb25zZRIPCgdtZXNzYWdlGAEgASgJEhUKDWF2ZXJhZ2Vfc2NvcmUYAiABKAJC3wEKFWNvbS5yYXRpbmcucG91dGluZS52MUIMUG91dGluZVByb3RvUAFaUmdpdGh1Yi5jb20vZGR1emd1bi1zZWN1cml0eS9qdWcvanVnLW1vZGVsL2p1Zy1tb2RlbC1nby9yYXRpbmcvcG91dGluZS92MTtwb3V0aW5ldjGiAgNSUFiqAhFSYXRpbmcuUG91dGluZS5WMcoCEVJhdGluZ1xQb3V0aW5lXFYx4gIdUmF0aW5nXFBvdXRpbmVcVjFcR1BCTWV0YWRhdGHqAhNSYXRpbmc6OlBvdXRpbmU6OlYxYgZwcm90bzM");

/**
 * @generated from message rating.poutine.v1.Poutine
 */
export type Poutine = Message<"rating.poutine.v1.Poutine"> & {
  /**
   * @generated from field: string restaurant = 1;
   */
  restaurant: string;

  /**
   * @generated from field: uint32 cheese_squeakiness = 2;
   */
  cheeseSqueakiness: number;

  /**
   * @generated from field: uint32 gravy_thickness = 3;
   */
  gravyThickness: number;

  /**
   * @generated from field: uint32 fries_crispiness = 4;
   */
  friesCrispiness: number;

  /**
   * @generated from field: string size = 5;
   */
  size: string;

  /**
   * @generated from field: string comments = 6;
   */
  comments: string;
};

/**
 * Describes the message rating.poutine.v1.Poutine.
 * Use `create(PoutineSchema)` to create a new message.
 */
export const PoutineSchema: GenMessage<Poutine> = /*@__PURE__*/
  messageDesc(file_rating_poutine_v1_poutine, 0);

/**
 * @generated from message rating.poutine.v1.PoutineRequest
 */
export type PoutineRequest = Message<"rating.poutine.v1.PoutineRequest"> & {
  /**
   * @generated from field: rating.poutine.v1.Poutine poutine = 1;
   */
  poutine?: Poutine;
};

/**
 * Describes the message rating.poutine.v1.PoutineRequest.
 * Use `create(PoutineRequestSchema)` to create a new message.
 */
export const PoutineRequestSchema: GenMessage<PoutineRequest> = /*@__PURE__*/
  messageDesc(file_rating_poutine_v1_poutine, 1);

/**
 * @generated from message rating.poutine.v1.PoutineResponse
 */
export type PoutineResponse = Message<"rating.poutine.v1.PoutineResponse"> & {
  /**
   * @generated from field: string message = 1;
   */
  message: string;

  /**
   * @generated from field: float average_score = 2;
   */
  averageScore: number;
};

/**
 * Describes the message rating.poutine.v1.PoutineResponse.
 * Use `create(PoutineResponseSchema)` to create a new message.
 */
export const PoutineResponseSchema: GenMessage<PoutineResponse> = /*@__PURE__*/
  messageDesc(file_rating_poutine_v1_poutine, 2);

