// source: rating/poutine/v1/poutine.proto
/**
 * @fileoverview
 * @enhanceable
 * @suppress {missingRequire} reports error on implicit type usages.
 * @suppress {messageConventions} JS Compiler reports an error if a variable or
 *     field starts with 'MSG_' and isn't a translatable message.
 * @public
 */
// GENERATED CODE -- DO NOT EDIT!
/* eslint-disable */
// @ts-nocheck

var jspb = require('google-protobuf');
var goog = jspb;
var global = globalThis;

goog.exportSymbol('proto.rating.poutine.v1.Poutine', null, global);
/**
 * Generated by JsPbCodeGenerator.
 * @param {Array=} opt_data Optional initial data array, typically from a
 * server response, or constructed directly in Javascript. The array is used
 * in place and becomes part of the constructed object. It is not cloned.
 * If no data is provided, the constructed object will be empty, but still
 * valid.
 * @extends {jspb.Message}
 * @constructor
 */
proto.rating.poutine.v1.Poutine = function(opt_data) {
  jspb.Message.initialize(this, opt_data, 0, -1, null, null);
};
goog.inherits(proto.rating.poutine.v1.Poutine, jspb.Message);
if (goog.DEBUG && !COMPILED) {
  /**
   * @public
   * @override
   */
  proto.rating.poutine.v1.Poutine.displayName = 'proto.rating.poutine.v1.Poutine';
}



if (jspb.Message.GENERATE_TO_OBJECT) {
/**
 * Creates an object representation of this proto.
 * Field names that are reserved in JavaScript and will be renamed to pb_name.
 * Optional fields that are not set will be set to undefined.
 * To access a reserved field use, foo.pb_<name>, eg, foo.pb_default.
 * For the list of reserved names please see:
 *     net/proto2/compiler/js/internal/generator.cc#kKeyword.
 * @param {boolean=} opt_includeInstance Deprecated. whether to include the
 *     JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @return {!Object}
 */
proto.rating.poutine.v1.Poutine.prototype.toObject = function(opt_includeInstance) {
  return proto.rating.poutine.v1.Poutine.toObject(opt_includeInstance, this);
};


/**
 * Static version of the {@see toObject} method.
 * @param {boolean|undefined} includeInstance Deprecated. Whether to include
 *     the JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @param {!proto.rating.poutine.v1.Poutine} msg The msg instance to transform.
 * @return {!Object}
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.rating.poutine.v1.Poutine.toObject = function(includeInstance, msg) {
  var f, obj = {
restaurant: jspb.Message.getFieldWithDefault(msg, 1, ""),
cheeseSqueakiness: jspb.Message.getFieldWithDefault(msg, 2, 0),
gravyThickness: jspb.Message.getFieldWithDefault(msg, 3, 0),
friesCrispiness: jspb.Message.getFieldWithDefault(msg, 4, 0),
size: jspb.Message.getFieldWithDefault(msg, 5, ""),
comments: jspb.Message.getFieldWithDefault(msg, 6, "")
  };

  if (includeInstance) {
    obj.$jspbMessageInstance = msg;
  }
  return obj;
};
}


/**
 * Deserializes binary data (in protobuf wire format).
 * @param {jspb.binary.bytesource.ByteSource} bytes The bytes to deserialize.
 * @return {!proto.rating.poutine.v1.Poutine}
 */
proto.rating.poutine.v1.Poutine.deserializeBinary = function(bytes) {
  var reader = new jspb.BinaryReader(bytes);
  var msg = new proto.rating.poutine.v1.Poutine;
  return proto.rating.poutine.v1.Poutine.deserializeBinaryFromReader(msg, reader);
};


/**
 * Deserializes binary data (in protobuf wire format) from the
 * given reader into the given message object.
 * @param {!proto.rating.poutine.v1.Poutine} msg The message object to deserialize into.
 * @param {!jspb.BinaryReader} reader The BinaryReader to use.
 * @return {!proto.rating.poutine.v1.Poutine}
 */
proto.rating.poutine.v1.Poutine.deserializeBinaryFromReader = function(msg, reader) {
  while (reader.nextField()) {
    if (reader.isEndGroup()) {
      break;
    }
    var field = reader.getFieldNumber();
    switch (field) {
    case 1:
      var value = /** @type {string} */ (reader.readStringRequireUtf8());
      msg.setRestaurant(value);
      break;
    case 2:
      var value = /** @type {number} */ (reader.readUint32());
      msg.setCheeseSqueakiness(value);
      break;
    case 3:
      var value = /** @type {number} */ (reader.readUint32());
      msg.setGravyThickness(value);
      break;
    case 4:
      var value = /** @type {number} */ (reader.readUint32());
      msg.setFriesCrispiness(value);
      break;
    case 5:
      var value = /** @type {string} */ (reader.readStringRequireUtf8());
      msg.setSize(value);
      break;
    case 6:
      var value = /** @type {string} */ (reader.readStringRequireUtf8());
      msg.setComments(value);
      break;
    default:
      reader.skipField();
      break;
    }
  }
  return msg;
};


/**
 * Serializes the message to binary data (in protobuf wire format).
 * @return {!Uint8Array}
 */
proto.rating.poutine.v1.Poutine.prototype.serializeBinary = function() {
  var writer = new jspb.BinaryWriter();
  proto.rating.poutine.v1.Poutine.serializeBinaryToWriter(this, writer);
  return writer.getResultBuffer();
};


/**
 * Serializes the given message to binary data (in protobuf wire
 * format), writing to the given BinaryWriter.
 * @param {!proto.rating.poutine.v1.Poutine} message
 * @param {!jspb.BinaryWriter} writer
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.rating.poutine.v1.Poutine.serializeBinaryToWriter = function(message, writer) {
  var f = undefined;
  f = message.getRestaurant();
  if (f.length > 0) {
    writer.writeString(
      1,
      f
    );
  }
  f = message.getCheeseSqueakiness();
  if (f !== 0) {
    writer.writeUint32(
      2,
      f
    );
  }
  f = message.getGravyThickness();
  if (f !== 0) {
    writer.writeUint32(
      3,
      f
    );
  }
  f = message.getFriesCrispiness();
  if (f !== 0) {
    writer.writeUint32(
      4,
      f
    );
  }
  f = message.getSize();
  if (f.length > 0) {
    writer.writeString(
      5,
      f
    );
  }
  f = message.getComments();
  if (f.length > 0) {
    writer.writeString(
      6,
      f
    );
  }
};


/**
 * optional string restaurant = 1;
 * @return {string}
 */
proto.rating.poutine.v1.Poutine.prototype.getRestaurant = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 1, ""));
};


/**
 * @param {string} value
 * @return {!proto.rating.poutine.v1.Poutine} returns this
 */
proto.rating.poutine.v1.Poutine.prototype.setRestaurant = function(value) {
  return jspb.Message.setProto3StringField(this, 1, value);
};


/**
 * optional uint32 cheese_squeakiness = 2;
 * @return {number}
 */
proto.rating.poutine.v1.Poutine.prototype.getCheeseSqueakiness = function() {
  return /** @type {number} */ (jspb.Message.getFieldWithDefault(this, 2, 0));
};


/**
 * @param {number} value
 * @return {!proto.rating.poutine.v1.Poutine} returns this
 */
proto.rating.poutine.v1.Poutine.prototype.setCheeseSqueakiness = function(value) {
  return jspb.Message.setProto3IntField(this, 2, value);
};


/**
 * optional uint32 gravy_thickness = 3;
 * @return {number}
 */
proto.rating.poutine.v1.Poutine.prototype.getGravyThickness = function() {
  return /** @type {number} */ (jspb.Message.getFieldWithDefault(this, 3, 0));
};


/**
 * @param {number} value
 * @return {!proto.rating.poutine.v1.Poutine} returns this
 */
proto.rating.poutine.v1.Poutine.prototype.setGravyThickness = function(value) {
  return jspb.Message.setProto3IntField(this, 3, value);
};


/**
 * optional uint32 fries_crispiness = 4;
 * @return {number}
 */
proto.rating.poutine.v1.Poutine.prototype.getFriesCrispiness = function() {
  return /** @type {number} */ (jspb.Message.getFieldWithDefault(this, 4, 0));
};


/**
 * @param {number} value
 * @return {!proto.rating.poutine.v1.Poutine} returns this
 */
proto.rating.poutine.v1.Poutine.prototype.setFriesCrispiness = function(value) {
  return jspb.Message.setProto3IntField(this, 4, value);
};


/**
 * optional string size = 5;
 * @return {string}
 */
proto.rating.poutine.v1.Poutine.prototype.getSize = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 5, ""));
};


/**
 * @param {string} value
 * @return {!proto.rating.poutine.v1.Poutine} returns this
 */
proto.rating.poutine.v1.Poutine.prototype.setSize = function(value) {
  return jspb.Message.setProto3StringField(this, 5, value);
};


/**
 * optional string comments = 6;
 * @return {string}
 */
proto.rating.poutine.v1.Poutine.prototype.getComments = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 6, ""));
};


/**
 * @param {string} value
 * @return {!proto.rating.poutine.v1.Poutine} returns this
 */
proto.rating.poutine.v1.Poutine.prototype.setComments = function(value) {
  return jspb.Message.setProto3StringField(this, 6, value);
};


goog.object.extend(exports, proto.rating.poutine.v1);
