// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: rating/consent/v1/consent.proto

// Protobuf Java Version: 3.25.3
package com.rating.consent.v1;

public interface ConsentOrBuilder extends
    // @@protoc_insertion_point(interface_extends:rating.consent.v1.Consent)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string email = 1 [json_name = "email", (.buf.validate.field) = { ... }</code>
   * @return The email.
   */
  java.lang.String getEmail();
  /**
   * <code>string email = 1 [json_name = "email", (.buf.validate.field) = { ... }</code>
   * @return The bytes for email.
   */
  com.google.protobuf.ByteString
      getEmailBytes();

  /**
   * <code>bool consent = 2 [json_name = "consent", (.buf.validate.field) = { ... }</code>
   * @return The consent.
   */
  boolean getConsent();
}
