// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: rating/consent/v1/consent.proto

// Protobuf Java Version: 3.25.3
package com.rating.consent.v1;

/**
 * Protobuf type {@code rating.consent.v1.ConsentRequest}
 */
public final class ConsentRequest extends
    com.google.protobuf.GeneratedMessageV3 implements
    // @@protoc_insertion_point(message_implements:rating.consent.v1.ConsentRequest)
    ConsentRequestOrBuilder {
private static final long serialVersionUID = 0L;
  // Use ConsentRequest.newBuilder() to construct.
  private ConsentRequest(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
    super(builder);
  }
  private ConsentRequest() {
  }

  @java.lang.Override
  @SuppressWarnings({"unused"})
  protected java.lang.Object newInstance(
      UnusedPrivateParameter unused) {
    return new ConsentRequest();
  }

  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return com.rating.consent.v1.ConsentProto.internal_static_rating_consent_v1_ConsentRequest_descriptor;
  }

  @java.lang.Override
  protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internalGetFieldAccessorTable() {
    return com.rating.consent.v1.ConsentProto.internal_static_rating_consent_v1_ConsentRequest_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            com.rating.consent.v1.ConsentRequest.class, com.rating.consent.v1.ConsentRequest.Builder.class);
  }

  private int bitField0_;
  public static final int CONSENT_FIELD_NUMBER = 1;
  private com.rating.consent.v1.Consent consent_;
  /**
   * <code>.rating.consent.v1.Consent consent = 1 [json_name = "consent"];</code>
   * @return Whether the consent field is set.
   */
  @java.lang.Override
  public boolean hasConsent() {
    return ((bitField0_ & 0x00000001) != 0);
  }
  /**
   * <code>.rating.consent.v1.Consent consent = 1 [json_name = "consent"];</code>
   * @return The consent.
   */
  @java.lang.Override
  public com.rating.consent.v1.Consent getConsent() {
    return consent_ == null ? com.rating.consent.v1.Consent.getDefaultInstance() : consent_;
  }
  /**
   * <code>.rating.consent.v1.Consent consent = 1 [json_name = "consent"];</code>
   */
  @java.lang.Override
  public com.rating.consent.v1.ConsentOrBuilder getConsentOrBuilder() {
    return consent_ == null ? com.rating.consent.v1.Consent.getDefaultInstance() : consent_;
  }

  private byte memoizedIsInitialized = -1;
  @java.lang.Override
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  @java.lang.Override
  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    if (((bitField0_ & 0x00000001) != 0)) {
      output.writeMessage(1, getConsent());
    }
    getUnknownFields().writeTo(output);
  }

  @java.lang.Override
  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    if (((bitField0_ & 0x00000001) != 0)) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(1, getConsent());
    }
    size += getUnknownFields().getSerializedSize();
    memoizedSize = size;
    return size;
  }

  @java.lang.Override
  public boolean equals(final java.lang.Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof com.rating.consent.v1.ConsentRequest)) {
      return super.equals(obj);
    }
    com.rating.consent.v1.ConsentRequest other = (com.rating.consent.v1.ConsentRequest) obj;

    if (hasConsent() != other.hasConsent()) return false;
    if (hasConsent()) {
      if (!getConsent()
          .equals(other.getConsent())) return false;
    }
    if (!getUnknownFields().equals(other.getUnknownFields())) return false;
    return true;
  }

  @java.lang.Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptor().hashCode();
    if (hasConsent()) {
      hash = (37 * hash) + CONSENT_FIELD_NUMBER;
      hash = (53 * hash) + getConsent().hashCode();
    }
    hash = (29 * hash) + getUnknownFields().hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static com.rating.consent.v1.ConsentRequest parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.rating.consent.v1.ConsentRequest parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.rating.consent.v1.ConsentRequest parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.rating.consent.v1.ConsentRequest parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.rating.consent.v1.ConsentRequest parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.rating.consent.v1.ConsentRequest parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.rating.consent.v1.ConsentRequest parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static com.rating.consent.v1.ConsentRequest parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  public static com.rating.consent.v1.ConsentRequest parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input);
  }

  public static com.rating.consent.v1.ConsentRequest parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static com.rating.consent.v1.ConsentRequest parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static com.rating.consent.v1.ConsentRequest parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  @java.lang.Override
  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(com.rating.consent.v1.ConsentRequest prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  @java.lang.Override
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @java.lang.Override
  protected Builder newBuilderForType(
      com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * Protobuf type {@code rating.consent.v1.ConsentRequest}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:rating.consent.v1.ConsentRequest)
      com.rating.consent.v1.ConsentRequestOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.rating.consent.v1.ConsentProto.internal_static_rating_consent_v1_ConsentRequest_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.rating.consent.v1.ConsentProto.internal_static_rating_consent_v1_ConsentRequest_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.rating.consent.v1.ConsentRequest.class, com.rating.consent.v1.ConsentRequest.Builder.class);
    }

    // Construct using com.rating.consent.v1.ConsentRequest.newBuilder()
    private Builder() {
      maybeForceBuilderInitialization();
    }

    private Builder(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      super(parent);
      maybeForceBuilderInitialization();
    }
    private void maybeForceBuilderInitialization() {
      if (com.google.protobuf.GeneratedMessageV3
              .alwaysUseFieldBuilders) {
        getConsentFieldBuilder();
      }
    }
    @java.lang.Override
    public Builder clear() {
      super.clear();
      bitField0_ = 0;
      consent_ = null;
      if (consentBuilder_ != null) {
        consentBuilder_.dispose();
        consentBuilder_ = null;
      }
      return this;
    }

    @java.lang.Override
    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return com.rating.consent.v1.ConsentProto.internal_static_rating_consent_v1_ConsentRequest_descriptor;
    }

    @java.lang.Override
    public com.rating.consent.v1.ConsentRequest getDefaultInstanceForType() {
      return com.rating.consent.v1.ConsentRequest.getDefaultInstance();
    }

    @java.lang.Override
    public com.rating.consent.v1.ConsentRequest build() {
      com.rating.consent.v1.ConsentRequest result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    @java.lang.Override
    public com.rating.consent.v1.ConsentRequest buildPartial() {
      com.rating.consent.v1.ConsentRequest result = new com.rating.consent.v1.ConsentRequest(this);
      if (bitField0_ != 0) { buildPartial0(result); }
      onBuilt();
      return result;
    }

    private void buildPartial0(com.rating.consent.v1.ConsentRequest result) {
      int from_bitField0_ = bitField0_;
      int to_bitField0_ = 0;
      if (((from_bitField0_ & 0x00000001) != 0)) {
        result.consent_ = consentBuilder_ == null
            ? consent_
            : consentBuilder_.build();
        to_bitField0_ |= 0x00000001;
      }
      result.bitField0_ |= to_bitField0_;
    }

    @java.lang.Override
    public Builder clone() {
      return super.clone();
    }
    @java.lang.Override
    public Builder setField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return super.setField(field, value);
    }
    @java.lang.Override
    public Builder clearField(
        com.google.protobuf.Descriptors.FieldDescriptor field) {
      return super.clearField(field);
    }
    @java.lang.Override
    public Builder clearOneof(
        com.google.protobuf.Descriptors.OneofDescriptor oneof) {
      return super.clearOneof(oneof);
    }
    @java.lang.Override
    public Builder setRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        int index, java.lang.Object value) {
      return super.setRepeatedField(field, index, value);
    }
    @java.lang.Override
    public Builder addRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return super.addRepeatedField(field, value);
    }
    @java.lang.Override
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof com.rating.consent.v1.ConsentRequest) {
        return mergeFrom((com.rating.consent.v1.ConsentRequest)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(com.rating.consent.v1.ConsentRequest other) {
      if (other == com.rating.consent.v1.ConsentRequest.getDefaultInstance()) return this;
      if (other.hasConsent()) {
        mergeConsent(other.getConsent());
      }
      this.mergeUnknownFields(other.getUnknownFields());
      onChanged();
      return this;
    }

    @java.lang.Override
    public final boolean isInitialized() {
      return true;
    }

    @java.lang.Override
    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 10: {
              input.readMessage(
                  getConsentFieldBuilder().getBuilder(),
                  extensionRegistry);
              bitField0_ |= 0x00000001;
              break;
            } // case 10
            default: {
              if (!super.parseUnknownField(input, extensionRegistry, tag)) {
                done = true; // was an endgroup tag
              }
              break;
            } // default:
          } // switch (tag)
        } // while (!done)
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.unwrapIOException();
      } finally {
        onChanged();
      } // finally
      return this;
    }
    private int bitField0_;

    private com.rating.consent.v1.Consent consent_;
    private com.google.protobuf.SingleFieldBuilderV3<
        com.rating.consent.v1.Consent, com.rating.consent.v1.Consent.Builder, com.rating.consent.v1.ConsentOrBuilder> consentBuilder_;
    /**
     * <code>.rating.consent.v1.Consent consent = 1 [json_name = "consent"];</code>
     * @return Whether the consent field is set.
     */
    public boolean hasConsent() {
      return ((bitField0_ & 0x00000001) != 0);
    }
    /**
     * <code>.rating.consent.v1.Consent consent = 1 [json_name = "consent"];</code>
     * @return The consent.
     */
    public com.rating.consent.v1.Consent getConsent() {
      if (consentBuilder_ == null) {
        return consent_ == null ? com.rating.consent.v1.Consent.getDefaultInstance() : consent_;
      } else {
        return consentBuilder_.getMessage();
      }
    }
    /**
     * <code>.rating.consent.v1.Consent consent = 1 [json_name = "consent"];</code>
     */
    public Builder setConsent(com.rating.consent.v1.Consent value) {
      if (consentBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        consent_ = value;
      } else {
        consentBuilder_.setMessage(value);
      }
      bitField0_ |= 0x00000001;
      onChanged();
      return this;
    }
    /**
     * <code>.rating.consent.v1.Consent consent = 1 [json_name = "consent"];</code>
     */
    public Builder setConsent(
        com.rating.consent.v1.Consent.Builder builderForValue) {
      if (consentBuilder_ == null) {
        consent_ = builderForValue.build();
      } else {
        consentBuilder_.setMessage(builderForValue.build());
      }
      bitField0_ |= 0x00000001;
      onChanged();
      return this;
    }
    /**
     * <code>.rating.consent.v1.Consent consent = 1 [json_name = "consent"];</code>
     */
    public Builder mergeConsent(com.rating.consent.v1.Consent value) {
      if (consentBuilder_ == null) {
        if (((bitField0_ & 0x00000001) != 0) &&
          consent_ != null &&
          consent_ != com.rating.consent.v1.Consent.getDefaultInstance()) {
          getConsentBuilder().mergeFrom(value);
        } else {
          consent_ = value;
        }
      } else {
        consentBuilder_.mergeFrom(value);
      }
      if (consent_ != null) {
        bitField0_ |= 0x00000001;
        onChanged();
      }
      return this;
    }
    /**
     * <code>.rating.consent.v1.Consent consent = 1 [json_name = "consent"];</code>
     */
    public Builder clearConsent() {
      bitField0_ = (bitField0_ & ~0x00000001);
      consent_ = null;
      if (consentBuilder_ != null) {
        consentBuilder_.dispose();
        consentBuilder_ = null;
      }
      onChanged();
      return this;
    }
    /**
     * <code>.rating.consent.v1.Consent consent = 1 [json_name = "consent"];</code>
     */
    public com.rating.consent.v1.Consent.Builder getConsentBuilder() {
      bitField0_ |= 0x00000001;
      onChanged();
      return getConsentFieldBuilder().getBuilder();
    }
    /**
     * <code>.rating.consent.v1.Consent consent = 1 [json_name = "consent"];</code>
     */
    public com.rating.consent.v1.ConsentOrBuilder getConsentOrBuilder() {
      if (consentBuilder_ != null) {
        return consentBuilder_.getMessageOrBuilder();
      } else {
        return consent_ == null ?
            com.rating.consent.v1.Consent.getDefaultInstance() : consent_;
      }
    }
    /**
     * <code>.rating.consent.v1.Consent consent = 1 [json_name = "consent"];</code>
     */
    private com.google.protobuf.SingleFieldBuilderV3<
        com.rating.consent.v1.Consent, com.rating.consent.v1.Consent.Builder, com.rating.consent.v1.ConsentOrBuilder> 
        getConsentFieldBuilder() {
      if (consentBuilder_ == null) {
        consentBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
            com.rating.consent.v1.Consent, com.rating.consent.v1.Consent.Builder, com.rating.consent.v1.ConsentOrBuilder>(
                getConsent(),
                getParentForChildren(),
                isClean());
        consent_ = null;
      }
      return consentBuilder_;
    }
    @java.lang.Override
    public final Builder setUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.setUnknownFields(unknownFields);
    }

    @java.lang.Override
    public final Builder mergeUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.mergeUnknownFields(unknownFields);
    }


    // @@protoc_insertion_point(builder_scope:rating.consent.v1.ConsentRequest)
  }

  // @@protoc_insertion_point(class_scope:rating.consent.v1.ConsentRequest)
  private static final com.rating.consent.v1.ConsentRequest DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new com.rating.consent.v1.ConsentRequest();
  }

  public static com.rating.consent.v1.ConsentRequest getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<ConsentRequest>
      PARSER = new com.google.protobuf.AbstractParser<ConsentRequest>() {
    @java.lang.Override
    public ConsentRequest parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      Builder builder = newBuilder();
      try {
        builder.mergeFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(builder.buildPartial());
      } catch (com.google.protobuf.UninitializedMessageException e) {
        throw e.asInvalidProtocolBufferException().setUnfinishedMessage(builder.buildPartial());
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(e)
            .setUnfinishedMessage(builder.buildPartial());
      }
      return builder.buildPartial();
    }
  };

  public static com.google.protobuf.Parser<ConsentRequest> parser() {
    return PARSER;
  }

  @java.lang.Override
  public com.google.protobuf.Parser<ConsentRequest> getParserForType() {
    return PARSER;
  }

  @java.lang.Override
  public com.rating.consent.v1.ConsentRequest getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

