// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: rating/consent/v1/consent.proto
// Protobuf Java Version: 4.33.2

package com.rating.consent.v1;

@com.google.protobuf.Generated
public final class ConsentOuterClass extends com.google.protobuf.GeneratedFile {
  private ConsentOuterClass() {}
  static {
    com.google.protobuf.RuntimeVersion.validateProtobufGencodeVersion(
      com.google.protobuf.RuntimeVersion.RuntimeDomain.PUBLIC,
      /* major= */ 4,
      /* minor= */ 33,
      /* patch= */ 2,
      /* suffix= */ "",
      "ConsentOuterClass");
  }
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_rating_consent_v1_Consent_descriptor;
  static final 
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_rating_consent_v1_Consent_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_rating_consent_v1_ConsentRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_rating_consent_v1_ConsentRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_rating_consent_v1_ConsentResponse_descriptor;
  static final 
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_rating_consent_v1_ConsentResponse_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\037rating/consent/v1/consent.proto\022\021ratin" +
      "g.consent.v1\"9\n\007Consent\022\024\n\005email\030\001 \001(\tR\005" +
      "email\022\030\n\007consent\030\002 \001(\010R\007consent\"F\n\016Conse" +
      "ntRequest\0224\n\007consent\030\001 \001(\0132\032.rating.cons" +
      "ent.v1.ConsentR\007consent\"+\n\017ConsentRespon" +
      "se\022\030\n\007message\030\001 \001(\tR\007messageBm\n\025com.rati" +
      "ng.consent.v1P\001ZRgithub.com/dduzgun-secu" +
      "rity/jug/jug-model/jug-model-go/rating/c" +
      "onsent/v1;consentv1b\006proto3"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        });
    internal_static_rating_consent_v1_Consent_descriptor =
      getDescriptor().getMessageType(0);
    internal_static_rating_consent_v1_Consent_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_rating_consent_v1_Consent_descriptor,
        new java.lang.String[] { "Email", "Consent", });
    internal_static_rating_consent_v1_ConsentRequest_descriptor =
      getDescriptor().getMessageType(1);
    internal_static_rating_consent_v1_ConsentRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_rating_consent_v1_ConsentRequest_descriptor,
        new java.lang.String[] { "Consent", });
    internal_static_rating_consent_v1_ConsentResponse_descriptor =
      getDescriptor().getMessageType(2);
    internal_static_rating_consent_v1_ConsentResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_rating_consent_v1_ConsentResponse_descriptor,
        new java.lang.String[] { "Message", });
    descriptor.resolveAllFeaturesImmutable();
  }

  // @@protoc_insertion_point(outer_class_scope)
}
