// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: rating/consent/v1/consent.proto
// Protobuf Java Version: 4.33.2

package com.rating.consent.v1;

@com.google.protobuf.Generated
public final class ConsentProto extends com.google.protobuf.GeneratedFile {
  private ConsentProto() {}
  static {
    com.google.protobuf.RuntimeVersion.validateProtobufGencodeVersion(
      com.google.protobuf.RuntimeVersion.RuntimeDomain.PUBLIC,
      /* major= */ 4,
      /* minor= */ 33,
      /* patch= */ 2,
      /* suffix= */ "",
      "ConsentProto");
  }
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_rating_consent_v1_Consent_descriptor;
  static final 
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_rating_consent_v1_Consent_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\037rating/consent/v1/consent.proto\022\021ratin" +
      "g.consent.v1\"9\n\007Consent\022\024\n\005email\030\001 \001(\tR\005" +
      "email\022\030\n\007consent\030\002 \001(\010R\007consentB\337\001\n\025com." +
      "rating.consent.v1B\014ConsentProtoP\001ZRgithu" +
      "b.com/dduzgun-security/jug/jug-model/jug" +
      "-model-go/rating/consent/v1;consentv1\242\002\003" +
      "RCX\252\002\021Rating.Consent.V1\312\002\021Rating\\Consent" +
      "\\V1\342\002\035Rating\\Consent\\V1\\GPBMetadata\352\002\023Ra" +
      "ting::Consent::V1b\006proto3"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        });
    internal_static_rating_consent_v1_Consent_descriptor =
      getDescriptor().getMessageType(0);
    internal_static_rating_consent_v1_Consent_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_rating_consent_v1_Consent_descriptor,
        new java.lang.String[] { "Email", "Consent", });
    descriptor.resolveAllFeaturesImmutable();
  }

  // @@protoc_insertion_point(outer_class_scope)
}
