// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: rating/consent/v1/consent.proto

// Protobuf Java Version: 3.25.3
package com.rating.consent.v1;

public final class ConsentProto {
  private ConsentProto() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_rating_consent_v1_Consent_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_rating_consent_v1_Consent_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_rating_consent_v1_ConsentRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_rating_consent_v1_ConsentRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_rating_consent_v1_ConsentResponse_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_rating_consent_v1_ConsentResponse_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\037rating/consent/v1/consent.proto\022\021ratin" +
      "g.consent.v1\032\033buf/validate/validate.prot" +
      "o\"Q\n\007Consent\022 \n\005email\030\001 \001(\tB\n\272H\007r\002`\001\310\001\001R" +
      "\005email\022$\n\007consent\030\002 \001(\010B\n\272H\007j\002\010\001\310\001\001R\007con" +
      "sent\"F\n\016ConsentRequest\0224\n\007consent\030\001 \001(\0132" +
      "\032.rating.consent.v1.ConsentR\007consent\"+\n\017" +
      "ConsentResponse\022\030\n\007message\030\001 \001(\tR\007messag" +
      "eB\337\001\n\025com.rating.consent.v1B\014ConsentProt" +
      "oP\001ZRgithub.com/dduzgun-security/jug/jug" +
      "-model/jug-model-go/rating/consent/v1;co" +
      "nsentv1\242\002\003RCX\252\002\021Rating.Consent.V1\312\002\021Rati" +
      "ng\\Consent\\V1\342\002\035Rating\\Consent\\V1\\GPBMet" +
      "adata\352\002\023Rating::Consent::V1b\006proto3"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
          com.buf.validate.ValidateProto.getDescriptor(),
        });
    internal_static_rating_consent_v1_Consent_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_rating_consent_v1_Consent_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_rating_consent_v1_Consent_descriptor,
        new java.lang.String[] { "Email", "Consent", });
    internal_static_rating_consent_v1_ConsentRequest_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_rating_consent_v1_ConsentRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_rating_consent_v1_ConsentRequest_descriptor,
        new java.lang.String[] { "Consent", });
    internal_static_rating_consent_v1_ConsentResponse_descriptor =
      getDescriptor().getMessageTypes().get(2);
    internal_static_rating_consent_v1_ConsentResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_rating_consent_v1_ConsentResponse_descriptor,
        new java.lang.String[] { "Message", });
    com.google.protobuf.ExtensionRegistry registry =
        com.google.protobuf.ExtensionRegistry.newInstance();
    registry.add(com.buf.validate.ValidateProto.field);
    com.google.protobuf.Descriptors.FileDescriptor
        .internalUpdateFileDescriptor(descriptor, registry);
    com.buf.validate.ValidateProto.getDescriptor();
  }

  // @@protoc_insertion_point(outer_class_scope)
}
