// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: rating/consent/v1/consent.proto

// Protobuf Java Version: 3.25.3
package com.rating.consent.v1;

public interface ConsentResponseOrBuilder extends
    // @@protoc_insertion_point(interface_extends:rating.consent.v1.ConsentResponse)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string message = 1 [json_name = "message"];</code>
   * @return The message.
   */
  java.lang.String getMessage();
  /**
   * <code>string message = 1 [json_name = "message"];</code>
   * @return The bytes for message.
   */
  com.google.protobuf.ByteString
      getMessageBytes();
}
