// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: rating/consent/v1/consent.proto
// Protobuf Java Version: 4.33.2

package com.rating.consent.v1;

@com.google.protobuf.Generated
public interface ConsentOrBuilder extends
    // @@protoc_insertion_point(interface_extends:rating.consent.v1.Consent)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string email = 1 [json_name = "email"];</code>
   * @return The email.
   */
  java.lang.String getEmail();
  /**
   * <code>string email = 1 [json_name = "email"];</code>
   * @return The bytes for email.
   */
  com.google.protobuf.ByteString
      getEmailBytes();

  /**
   * <code>bool consent = 2 [json_name = "consent"];</code>
   * @return The consent.
   */
  boolean getConsent();
}
