// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: rating/consent/v1/consent.proto

// Protobuf Java Version: 3.25.3
package com.rating.consent.v1;

public interface ConsentRequestOrBuilder extends
    // @@protoc_insertion_point(interface_extends:rating.consent.v1.ConsentRequest)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>.rating.consent.v1.Consent consent = 1 [json_name = "consent"];</code>
   * @return Whether the consent field is set.
   */
  boolean hasConsent();
  /**
   * <code>.rating.consent.v1.Consent consent = 1 [json_name = "consent"];</code>
   * @return The consent.
   */
  com.rating.consent.v1.Consent getConsent();
  /**
   * <code>.rating.consent.v1.Consent consent = 1 [json_name = "consent"];</code>
   */
  com.rating.consent.v1.ConsentOrBuilder getConsentOrBuilder();
}
