// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: rating/poutine/v1/poutine.proto
// Protobuf Java Version: 4.33.1

package com.rating.poutine.v1;

/**
 * Protobuf type {@code rating.poutine.v1.GetRatingResponse}
 */
@com.google.protobuf.Generated
public final class GetRatingResponse extends
    com.google.protobuf.GeneratedMessage implements
    // @@protoc_insertion_point(message_implements:rating.poutine.v1.GetRatingResponse)
    GetRatingResponseOrBuilder {
private static final long serialVersionUID = 0L;
  static {
    com.google.protobuf.RuntimeVersion.validateProtobufGencodeVersion(
      com.google.protobuf.RuntimeVersion.RuntimeDomain.PUBLIC,
      /* major= */ 4,
      /* minor= */ 33,
      /* patch= */ 1,
      /* suffix= */ "",
      "GetRatingResponse");
  }
  // Use GetRatingResponse.newBuilder() to construct.
  private GetRatingResponse(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
    super(builder);
  }
  private GetRatingResponse() {
  }

  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return com.rating.poutine.v1.PoutineProto.internal_static_rating_poutine_v1_GetRatingResponse_descriptor;
  }

  @java.lang.Override
  protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internalGetFieldAccessorTable() {
    return com.rating.poutine.v1.PoutineProto.internal_static_rating_poutine_v1_GetRatingResponse_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            com.rating.poutine.v1.GetRatingResponse.class, com.rating.poutine.v1.GetRatingResponse.Builder.class);
  }

  private int bitField0_;
  public static final int RATING_FIELD_NUMBER = 1;
  private com.rating.poutine.v1.Poutine rating_;
  /**
   * <code>.rating.poutine.v1.Poutine rating = 1 [json_name = "rating"];</code>
   * @return Whether the rating field is set.
   */
  @java.lang.Override
  public boolean hasRating() {
    return ((bitField0_ & 0x00000001) != 0);
  }
  /**
   * <code>.rating.poutine.v1.Poutine rating = 1 [json_name = "rating"];</code>
   * @return The rating.
   */
  @java.lang.Override
  public com.rating.poutine.v1.Poutine getRating() {
    return rating_ == null ? com.rating.poutine.v1.Poutine.getDefaultInstance() : rating_;
  }
  /**
   * <code>.rating.poutine.v1.Poutine rating = 1 [json_name = "rating"];</code>
   */
  @java.lang.Override
  public com.rating.poutine.v1.PoutineOrBuilder getRatingOrBuilder() {
    return rating_ == null ? com.rating.poutine.v1.Poutine.getDefaultInstance() : rating_;
  }

  private byte memoizedIsInitialized = -1;
  @java.lang.Override
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  @java.lang.Override
  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    if (((bitField0_ & 0x00000001) != 0)) {
      output.writeMessage(1, getRating());
    }
    getUnknownFields().writeTo(output);
  }

  @java.lang.Override
  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    if (((bitField0_ & 0x00000001) != 0)) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(1, getRating());
    }
    size += getUnknownFields().getSerializedSize();
    memoizedSize = size;
    return size;
  }

  @java.lang.Override
  public boolean equals(final java.lang.Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof com.rating.poutine.v1.GetRatingResponse)) {
      return super.equals(obj);
    }
    com.rating.poutine.v1.GetRatingResponse other = (com.rating.poutine.v1.GetRatingResponse) obj;

    if (hasRating() != other.hasRating()) return false;
    if (hasRating()) {
      if (!getRating()
          .equals(other.getRating())) return false;
    }
    if (!getUnknownFields().equals(other.getUnknownFields())) return false;
    return true;
  }

  @java.lang.Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptor().hashCode();
    if (hasRating()) {
      hash = (37 * hash) + RATING_FIELD_NUMBER;
      hash = (53 * hash) + getRating().hashCode();
    }
    hash = (29 * hash) + getUnknownFields().hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static com.rating.poutine.v1.GetRatingResponse parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.rating.poutine.v1.GetRatingResponse parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.rating.poutine.v1.GetRatingResponse parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.rating.poutine.v1.GetRatingResponse parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.rating.poutine.v1.GetRatingResponse parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.rating.poutine.v1.GetRatingResponse parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.rating.poutine.v1.GetRatingResponse parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseWithIOException(PARSER, input);
  }
  public static com.rating.poutine.v1.GetRatingResponse parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  public static com.rating.poutine.v1.GetRatingResponse parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseDelimitedWithIOException(PARSER, input);
  }

  public static com.rating.poutine.v1.GetRatingResponse parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static com.rating.poutine.v1.GetRatingResponse parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseWithIOException(PARSER, input);
  }
  public static com.rating.poutine.v1.GetRatingResponse parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  @java.lang.Override
  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(com.rating.poutine.v1.GetRatingResponse prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  @java.lang.Override
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @java.lang.Override
  protected Builder newBuilderForType(
      com.google.protobuf.GeneratedMessage.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * Protobuf type {@code rating.poutine.v1.GetRatingResponse}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessage.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:rating.poutine.v1.GetRatingResponse)
      com.rating.poutine.v1.GetRatingResponseOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.rating.poutine.v1.PoutineProto.internal_static_rating_poutine_v1_GetRatingResponse_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.rating.poutine.v1.PoutineProto.internal_static_rating_poutine_v1_GetRatingResponse_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.rating.poutine.v1.GetRatingResponse.class, com.rating.poutine.v1.GetRatingResponse.Builder.class);
    }

    // Construct using com.rating.poutine.v1.GetRatingResponse.newBuilder()
    private Builder() {
      maybeForceBuilderInitialization();
    }

    private Builder(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      super(parent);
      maybeForceBuilderInitialization();
    }
    private void maybeForceBuilderInitialization() {
      if (com.google.protobuf.GeneratedMessage
              .alwaysUseFieldBuilders) {
        internalGetRatingFieldBuilder();
      }
    }
    @java.lang.Override
    public Builder clear() {
      super.clear();
      bitField0_ = 0;
      rating_ = null;
      if (ratingBuilder_ != null) {
        ratingBuilder_.dispose();
        ratingBuilder_ = null;
      }
      return this;
    }

    @java.lang.Override
    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return com.rating.poutine.v1.PoutineProto.internal_static_rating_poutine_v1_GetRatingResponse_descriptor;
    }

    @java.lang.Override
    public com.rating.poutine.v1.GetRatingResponse getDefaultInstanceForType() {
      return com.rating.poutine.v1.GetRatingResponse.getDefaultInstance();
    }

    @java.lang.Override
    public com.rating.poutine.v1.GetRatingResponse build() {
      com.rating.poutine.v1.GetRatingResponse result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    @java.lang.Override
    public com.rating.poutine.v1.GetRatingResponse buildPartial() {
      com.rating.poutine.v1.GetRatingResponse result = new com.rating.poutine.v1.GetRatingResponse(this);
      if (bitField0_ != 0) { buildPartial0(result); }
      onBuilt();
      return result;
    }

    private void buildPartial0(com.rating.poutine.v1.GetRatingResponse result) {
      int from_bitField0_ = bitField0_;
      int to_bitField0_ = 0;
      if (((from_bitField0_ & 0x00000001) != 0)) {
        result.rating_ = ratingBuilder_ == null
            ? rating_
            : ratingBuilder_.build();
        to_bitField0_ |= 0x00000001;
      }
      result.bitField0_ |= to_bitField0_;
    }

    @java.lang.Override
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof com.rating.poutine.v1.GetRatingResponse) {
        return mergeFrom((com.rating.poutine.v1.GetRatingResponse)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(com.rating.poutine.v1.GetRatingResponse other) {
      if (other == com.rating.poutine.v1.GetRatingResponse.getDefaultInstance()) return this;
      if (other.hasRating()) {
        mergeRating(other.getRating());
      }
      this.mergeUnknownFields(other.getUnknownFields());
      onChanged();
      return this;
    }

    @java.lang.Override
    public final boolean isInitialized() {
      return true;
    }

    @java.lang.Override
    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 10: {
              input.readMessage(
                  internalGetRatingFieldBuilder().getBuilder(),
                  extensionRegistry);
              bitField0_ |= 0x00000001;
              break;
            } // case 10
            default: {
              if (!super.parseUnknownField(input, extensionRegistry, tag)) {
                done = true; // was an endgroup tag
              }
              break;
            } // default:
          } // switch (tag)
        } // while (!done)
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.unwrapIOException();
      } finally {
        onChanged();
      } // finally
      return this;
    }
    private int bitField0_;

    private com.rating.poutine.v1.Poutine rating_;
    private com.google.protobuf.SingleFieldBuilder<
        com.rating.poutine.v1.Poutine, com.rating.poutine.v1.Poutine.Builder, com.rating.poutine.v1.PoutineOrBuilder> ratingBuilder_;
    /**
     * <code>.rating.poutine.v1.Poutine rating = 1 [json_name = "rating"];</code>
     * @return Whether the rating field is set.
     */
    public boolean hasRating() {
      return ((bitField0_ & 0x00000001) != 0);
    }
    /**
     * <code>.rating.poutine.v1.Poutine rating = 1 [json_name = "rating"];</code>
     * @return The rating.
     */
    public com.rating.poutine.v1.Poutine getRating() {
      if (ratingBuilder_ == null) {
        return rating_ == null ? com.rating.poutine.v1.Poutine.getDefaultInstance() : rating_;
      } else {
        return ratingBuilder_.getMessage();
      }
    }
    /**
     * <code>.rating.poutine.v1.Poutine rating = 1 [json_name = "rating"];</code>
     */
    public Builder setRating(com.rating.poutine.v1.Poutine value) {
      if (ratingBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        rating_ = value;
      } else {
        ratingBuilder_.setMessage(value);
      }
      bitField0_ |= 0x00000001;
      onChanged();
      return this;
    }
    /**
     * <code>.rating.poutine.v1.Poutine rating = 1 [json_name = "rating"];</code>
     */
    public Builder setRating(
        com.rating.poutine.v1.Poutine.Builder builderForValue) {
      if (ratingBuilder_ == null) {
        rating_ = builderForValue.build();
      } else {
        ratingBuilder_.setMessage(builderForValue.build());
      }
      bitField0_ |= 0x00000001;
      onChanged();
      return this;
    }
    /**
     * <code>.rating.poutine.v1.Poutine rating = 1 [json_name = "rating"];</code>
     */
    public Builder mergeRating(com.rating.poutine.v1.Poutine value) {
      if (ratingBuilder_ == null) {
        if (((bitField0_ & 0x00000001) != 0) &&
          rating_ != null &&
          rating_ != com.rating.poutine.v1.Poutine.getDefaultInstance()) {
          getRatingBuilder().mergeFrom(value);
        } else {
          rating_ = value;
        }
      } else {
        ratingBuilder_.mergeFrom(value);
      }
      if (rating_ != null) {
        bitField0_ |= 0x00000001;
        onChanged();
      }
      return this;
    }
    /**
     * <code>.rating.poutine.v1.Poutine rating = 1 [json_name = "rating"];</code>
     */
    public Builder clearRating() {
      bitField0_ = (bitField0_ & ~0x00000001);
      rating_ = null;
      if (ratingBuilder_ != null) {
        ratingBuilder_.dispose();
        ratingBuilder_ = null;
      }
      onChanged();
      return this;
    }
    /**
     * <code>.rating.poutine.v1.Poutine rating = 1 [json_name = "rating"];</code>
     */
    public com.rating.poutine.v1.Poutine.Builder getRatingBuilder() {
      bitField0_ |= 0x00000001;
      onChanged();
      return internalGetRatingFieldBuilder().getBuilder();
    }
    /**
     * <code>.rating.poutine.v1.Poutine rating = 1 [json_name = "rating"];</code>
     */
    public com.rating.poutine.v1.PoutineOrBuilder getRatingOrBuilder() {
      if (ratingBuilder_ != null) {
        return ratingBuilder_.getMessageOrBuilder();
      } else {
        return rating_ == null ?
            com.rating.poutine.v1.Poutine.getDefaultInstance() : rating_;
      }
    }
    /**
     * <code>.rating.poutine.v1.Poutine rating = 1 [json_name = "rating"];</code>
     */
    private com.google.protobuf.SingleFieldBuilder<
        com.rating.poutine.v1.Poutine, com.rating.poutine.v1.Poutine.Builder, com.rating.poutine.v1.PoutineOrBuilder> 
        internalGetRatingFieldBuilder() {
      if (ratingBuilder_ == null) {
        ratingBuilder_ = new com.google.protobuf.SingleFieldBuilder<
            com.rating.poutine.v1.Poutine, com.rating.poutine.v1.Poutine.Builder, com.rating.poutine.v1.PoutineOrBuilder>(
                getRating(),
                getParentForChildren(),
                isClean());
        rating_ = null;
      }
      return ratingBuilder_;
    }

    // @@protoc_insertion_point(builder_scope:rating.poutine.v1.GetRatingResponse)
  }

  // @@protoc_insertion_point(class_scope:rating.poutine.v1.GetRatingResponse)
  private static final com.rating.poutine.v1.GetRatingResponse DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new com.rating.poutine.v1.GetRatingResponse();
  }

  public static com.rating.poutine.v1.GetRatingResponse getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<GetRatingResponse>
      PARSER = new com.google.protobuf.AbstractParser<GetRatingResponse>() {
    @java.lang.Override
    public GetRatingResponse parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      Builder builder = newBuilder();
      try {
        builder.mergeFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(builder.buildPartial());
      } catch (com.google.protobuf.UninitializedMessageException e) {
        throw e.asInvalidProtocolBufferException().setUnfinishedMessage(builder.buildPartial());
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(e)
            .setUnfinishedMessage(builder.buildPartial());
      }
      return builder.buildPartial();
    }
  };

  public static com.google.protobuf.Parser<GetRatingResponse> parser() {
    return PARSER;
  }

  @java.lang.Override
  public com.google.protobuf.Parser<GetRatingResponse> getParserForType() {
    return PARSER;
  }

  @java.lang.Override
  public com.rating.poutine.v1.GetRatingResponse getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

