// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: rating/poutine/v1/poutine.proto
// Protobuf Java Version: 4.33.1

package com.rating.poutine.v1;

/**
 * Protobuf type {@code rating.poutine.v1.GetRatingRequest}
 */
@com.google.protobuf.Generated
public final class GetRatingRequest extends
    com.google.protobuf.GeneratedMessage implements
    // @@protoc_insertion_point(message_implements:rating.poutine.v1.GetRatingRequest)
    GetRatingRequestOrBuilder {
private static final long serialVersionUID = 0L;
  static {
    com.google.protobuf.RuntimeVersion.validateProtobufGencodeVersion(
      com.google.protobuf.RuntimeVersion.RuntimeDomain.PUBLIC,
      /* major= */ 4,
      /* minor= */ 33,
      /* patch= */ 1,
      /* suffix= */ "",
      "GetRatingRequest");
  }
  // Use GetRatingRequest.newBuilder() to construct.
  private GetRatingRequest(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
    super(builder);
  }
  private GetRatingRequest() {
  }

  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return com.rating.poutine.v1.PoutineProto.internal_static_rating_poutine_v1_GetRatingRequest_descriptor;
  }

  @java.lang.Override
  protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internalGetFieldAccessorTable() {
    return com.rating.poutine.v1.PoutineProto.internal_static_rating_poutine_v1_GetRatingRequest_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            com.rating.poutine.v1.GetRatingRequest.class, com.rating.poutine.v1.GetRatingRequest.Builder.class);
  }

  public static final int RATING_ID_FIELD_NUMBER = 1;
  private long ratingId_ = 0L;
  /**
   * <code>int64 rating_id = 1 [json_name = "ratingId"];</code>
   * @return The ratingId.
   */
  @java.lang.Override
  public long getRatingId() {
    return ratingId_;
  }

  private byte memoizedIsInitialized = -1;
  @java.lang.Override
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  @java.lang.Override
  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    if (ratingId_ != 0L) {
      output.writeInt64(1, ratingId_);
    }
    getUnknownFields().writeTo(output);
  }

  @java.lang.Override
  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    if (ratingId_ != 0L) {
      size += com.google.protobuf.CodedOutputStream
        .computeInt64Size(1, ratingId_);
    }
    size += getUnknownFields().getSerializedSize();
    memoizedSize = size;
    return size;
  }

  @java.lang.Override
  public boolean equals(final java.lang.Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof com.rating.poutine.v1.GetRatingRequest)) {
      return super.equals(obj);
    }
    com.rating.poutine.v1.GetRatingRequest other = (com.rating.poutine.v1.GetRatingRequest) obj;

    if (getRatingId()
        != other.getRatingId()) return false;
    if (!getUnknownFields().equals(other.getUnknownFields())) return false;
    return true;
  }

  @java.lang.Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptor().hashCode();
    hash = (37 * hash) + RATING_ID_FIELD_NUMBER;
    hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
        getRatingId());
    hash = (29 * hash) + getUnknownFields().hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static com.rating.poutine.v1.GetRatingRequest parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.rating.poutine.v1.GetRatingRequest parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.rating.poutine.v1.GetRatingRequest parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.rating.poutine.v1.GetRatingRequest parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.rating.poutine.v1.GetRatingRequest parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.rating.poutine.v1.GetRatingRequest parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.rating.poutine.v1.GetRatingRequest parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseWithIOException(PARSER, input);
  }
  public static com.rating.poutine.v1.GetRatingRequest parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  public static com.rating.poutine.v1.GetRatingRequest parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseDelimitedWithIOException(PARSER, input);
  }

  public static com.rating.poutine.v1.GetRatingRequest parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static com.rating.poutine.v1.GetRatingRequest parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseWithIOException(PARSER, input);
  }
  public static com.rating.poutine.v1.GetRatingRequest parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  @java.lang.Override
  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(com.rating.poutine.v1.GetRatingRequest prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  @java.lang.Override
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @java.lang.Override
  protected Builder newBuilderForType(
      com.google.protobuf.GeneratedMessage.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * Protobuf type {@code rating.poutine.v1.GetRatingRequest}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessage.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:rating.poutine.v1.GetRatingRequest)
      com.rating.poutine.v1.GetRatingRequestOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.rating.poutine.v1.PoutineProto.internal_static_rating_poutine_v1_GetRatingRequest_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.rating.poutine.v1.PoutineProto.internal_static_rating_poutine_v1_GetRatingRequest_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.rating.poutine.v1.GetRatingRequest.class, com.rating.poutine.v1.GetRatingRequest.Builder.class);
    }

    // Construct using com.rating.poutine.v1.GetRatingRequest.newBuilder()
    private Builder() {

    }

    private Builder(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      super(parent);

    }
    @java.lang.Override
    public Builder clear() {
      super.clear();
      bitField0_ = 0;
      ratingId_ = 0L;
      return this;
    }

    @java.lang.Override
    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return com.rating.poutine.v1.PoutineProto.internal_static_rating_poutine_v1_GetRatingRequest_descriptor;
    }

    @java.lang.Override
    public com.rating.poutine.v1.GetRatingRequest getDefaultInstanceForType() {
      return com.rating.poutine.v1.GetRatingRequest.getDefaultInstance();
    }

    @java.lang.Override
    public com.rating.poutine.v1.GetRatingRequest build() {
      com.rating.poutine.v1.GetRatingRequest result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    @java.lang.Override
    public com.rating.poutine.v1.GetRatingRequest buildPartial() {
      com.rating.poutine.v1.GetRatingRequest result = new com.rating.poutine.v1.GetRatingRequest(this);
      if (bitField0_ != 0) { buildPartial0(result); }
      onBuilt();
      return result;
    }

    private void buildPartial0(com.rating.poutine.v1.GetRatingRequest result) {
      int from_bitField0_ = bitField0_;
      if (((from_bitField0_ & 0x00000001) != 0)) {
        result.ratingId_ = ratingId_;
      }
    }

    @java.lang.Override
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof com.rating.poutine.v1.GetRatingRequest) {
        return mergeFrom((com.rating.poutine.v1.GetRatingRequest)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(com.rating.poutine.v1.GetRatingRequest other) {
      if (other == com.rating.poutine.v1.GetRatingRequest.getDefaultInstance()) return this;
      if (other.getRatingId() != 0L) {
        setRatingId(other.getRatingId());
      }
      this.mergeUnknownFields(other.getUnknownFields());
      onChanged();
      return this;
    }

    @java.lang.Override
    public final boolean isInitialized() {
      return true;
    }

    @java.lang.Override
    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 8: {
              ratingId_ = input.readInt64();
              bitField0_ |= 0x00000001;
              break;
            } // case 8
            default: {
              if (!super.parseUnknownField(input, extensionRegistry, tag)) {
                done = true; // was an endgroup tag
              }
              break;
            } // default:
          } // switch (tag)
        } // while (!done)
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.unwrapIOException();
      } finally {
        onChanged();
      } // finally
      return this;
    }
    private int bitField0_;

    private long ratingId_ ;
    /**
     * <code>int64 rating_id = 1 [json_name = "ratingId"];</code>
     * @return The ratingId.
     */
    @java.lang.Override
    public long getRatingId() {
      return ratingId_;
    }
    /**
     * <code>int64 rating_id = 1 [json_name = "ratingId"];</code>
     * @param value The ratingId to set.
     * @return This builder for chaining.
     */
    public Builder setRatingId(long value) {

      ratingId_ = value;
      bitField0_ |= 0x00000001;
      onChanged();
      return this;
    }
    /**
     * <code>int64 rating_id = 1 [json_name = "ratingId"];</code>
     * @return This builder for chaining.
     */
    public Builder clearRatingId() {
      bitField0_ = (bitField0_ & ~0x00000001);
      ratingId_ = 0L;
      onChanged();
      return this;
    }

    // @@protoc_insertion_point(builder_scope:rating.poutine.v1.GetRatingRequest)
  }

  // @@protoc_insertion_point(class_scope:rating.poutine.v1.GetRatingRequest)
  private static final com.rating.poutine.v1.GetRatingRequest DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new com.rating.poutine.v1.GetRatingRequest();
  }

  public static com.rating.poutine.v1.GetRatingRequest getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<GetRatingRequest>
      PARSER = new com.google.protobuf.AbstractParser<GetRatingRequest>() {
    @java.lang.Override
    public GetRatingRequest parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      Builder builder = newBuilder();
      try {
        builder.mergeFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(builder.buildPartial());
      } catch (com.google.protobuf.UninitializedMessageException e) {
        throw e.asInvalidProtocolBufferException().setUnfinishedMessage(builder.buildPartial());
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(e)
            .setUnfinishedMessage(builder.buildPartial());
      }
      return builder.buildPartial();
    }
  };

  public static com.google.protobuf.Parser<GetRatingRequest> parser() {
    return PARSER;
  }

  @java.lang.Override
  public com.google.protobuf.Parser<GetRatingRequest> getParserForType() {
    return PARSER;
  }

  @java.lang.Override
  public com.rating.poutine.v1.GetRatingRequest getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

