// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: rating/poutine/v1/poutine.proto
// Protobuf Java Version: 4.33.1

package com.rating.poutine.v1;

@com.google.protobuf.Generated
public interface GetRatingResponseOrBuilder extends
    // @@protoc_insertion_point(interface_extends:rating.poutine.v1.GetRatingResponse)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>.rating.poutine.v1.Poutine rating = 1 [json_name = "rating"];</code>
   * @return Whether the rating field is set.
   */
  boolean hasRating();
  /**
   * <code>.rating.poutine.v1.Poutine rating = 1 [json_name = "rating"];</code>
   * @return The rating.
   */
  com.rating.poutine.v1.Poutine getRating();
  /**
   * <code>.rating.poutine.v1.Poutine rating = 1 [json_name = "rating"];</code>
   */
  com.rating.poutine.v1.PoutineOrBuilder getRatingOrBuilder();
}
