// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: rating/poutine/v1/poutine.proto
// Protobuf Java Version: 4.33.1

package com.rating.poutine.v1;

@com.google.protobuf.Generated
public interface GetRatingRequestOrBuilder extends
    // @@protoc_insertion_point(interface_extends:rating.poutine.v1.GetRatingRequest)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>int64 rating_id = 1 [json_name = "ratingId"];</code>
   * @return The ratingId.
   */
  long getRatingId();
}
