// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: rating/poutine/v1/poutine.proto
// Protobuf Java Version: 4.33.1

package com.rating.poutine.v1;

/**
 * Protobuf type {@code rating.poutine.v1.ListRatingsByRestaurantResponse}
 */
@com.google.protobuf.Generated
public final class ListRatingsByRestaurantResponse extends
    com.google.protobuf.GeneratedMessage implements
    // @@protoc_insertion_point(message_implements:rating.poutine.v1.ListRatingsByRestaurantResponse)
    ListRatingsByRestaurantResponseOrBuilder {
private static final long serialVersionUID = 0L;
  static {
    com.google.protobuf.RuntimeVersion.validateProtobufGencodeVersion(
      com.google.protobuf.RuntimeVersion.RuntimeDomain.PUBLIC,
      /* major= */ 4,
      /* minor= */ 33,
      /* patch= */ 1,
      /* suffix= */ "",
      "ListRatingsByRestaurantResponse");
  }
  // Use ListRatingsByRestaurantResponse.newBuilder() to construct.
  private ListRatingsByRestaurantResponse(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
    super(builder);
  }
  private ListRatingsByRestaurantResponse() {
    ratings_ = java.util.Collections.emptyList();
  }

  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return com.rating.poutine.v1.PoutineProto.internal_static_rating_poutine_v1_ListRatingsByRestaurantResponse_descriptor;
  }

  @java.lang.Override
  protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internalGetFieldAccessorTable() {
    return com.rating.poutine.v1.PoutineProto.internal_static_rating_poutine_v1_ListRatingsByRestaurantResponse_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            com.rating.poutine.v1.ListRatingsByRestaurantResponse.class, com.rating.poutine.v1.ListRatingsByRestaurantResponse.Builder.class);
  }

  public static final int RATINGS_FIELD_NUMBER = 1;
  @SuppressWarnings("serial")
  private java.util.List<com.rating.poutine.v1.Poutine> ratings_;
  /**
   * <code>repeated .rating.poutine.v1.Poutine ratings = 1 [json_name = "ratings"];</code>
   */
  @java.lang.Override
  public java.util.List<com.rating.poutine.v1.Poutine> getRatingsList() {
    return ratings_;
  }
  /**
   * <code>repeated .rating.poutine.v1.Poutine ratings = 1 [json_name = "ratings"];</code>
   */
  @java.lang.Override
  public java.util.List<? extends com.rating.poutine.v1.PoutineOrBuilder> 
      getRatingsOrBuilderList() {
    return ratings_;
  }
  /**
   * <code>repeated .rating.poutine.v1.Poutine ratings = 1 [json_name = "ratings"];</code>
   */
  @java.lang.Override
  public int getRatingsCount() {
    return ratings_.size();
  }
  /**
   * <code>repeated .rating.poutine.v1.Poutine ratings = 1 [json_name = "ratings"];</code>
   */
  @java.lang.Override
  public com.rating.poutine.v1.Poutine getRatings(int index) {
    return ratings_.get(index);
  }
  /**
   * <code>repeated .rating.poutine.v1.Poutine ratings = 1 [json_name = "ratings"];</code>
   */
  @java.lang.Override
  public com.rating.poutine.v1.PoutineOrBuilder getRatingsOrBuilder(
      int index) {
    return ratings_.get(index);
  }

  private byte memoizedIsInitialized = -1;
  @java.lang.Override
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  @java.lang.Override
  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    for (int i = 0; i < ratings_.size(); i++) {
      output.writeMessage(1, ratings_.get(i));
    }
    getUnknownFields().writeTo(output);
  }

  @java.lang.Override
  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    for (int i = 0; i < ratings_.size(); i++) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(1, ratings_.get(i));
    }
    size += getUnknownFields().getSerializedSize();
    memoizedSize = size;
    return size;
  }

  @java.lang.Override
  public boolean equals(final java.lang.Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof com.rating.poutine.v1.ListRatingsByRestaurantResponse)) {
      return super.equals(obj);
    }
    com.rating.poutine.v1.ListRatingsByRestaurantResponse other = (com.rating.poutine.v1.ListRatingsByRestaurantResponse) obj;

    if (!getRatingsList()
        .equals(other.getRatingsList())) return false;
    if (!getUnknownFields().equals(other.getUnknownFields())) return false;
    return true;
  }

  @java.lang.Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptor().hashCode();
    if (getRatingsCount() > 0) {
      hash = (37 * hash) + RATINGS_FIELD_NUMBER;
      hash = (53 * hash) + getRatingsList().hashCode();
    }
    hash = (29 * hash) + getUnknownFields().hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static com.rating.poutine.v1.ListRatingsByRestaurantResponse parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.rating.poutine.v1.ListRatingsByRestaurantResponse parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.rating.poutine.v1.ListRatingsByRestaurantResponse parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.rating.poutine.v1.ListRatingsByRestaurantResponse parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.rating.poutine.v1.ListRatingsByRestaurantResponse parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.rating.poutine.v1.ListRatingsByRestaurantResponse parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.rating.poutine.v1.ListRatingsByRestaurantResponse parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseWithIOException(PARSER, input);
  }
  public static com.rating.poutine.v1.ListRatingsByRestaurantResponse parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  public static com.rating.poutine.v1.ListRatingsByRestaurantResponse parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseDelimitedWithIOException(PARSER, input);
  }

  public static com.rating.poutine.v1.ListRatingsByRestaurantResponse parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static com.rating.poutine.v1.ListRatingsByRestaurantResponse parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseWithIOException(PARSER, input);
  }
  public static com.rating.poutine.v1.ListRatingsByRestaurantResponse parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  @java.lang.Override
  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(com.rating.poutine.v1.ListRatingsByRestaurantResponse prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  @java.lang.Override
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @java.lang.Override
  protected Builder newBuilderForType(
      com.google.protobuf.GeneratedMessage.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * Protobuf type {@code rating.poutine.v1.ListRatingsByRestaurantResponse}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessage.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:rating.poutine.v1.ListRatingsByRestaurantResponse)
      com.rating.poutine.v1.ListRatingsByRestaurantResponseOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.rating.poutine.v1.PoutineProto.internal_static_rating_poutine_v1_ListRatingsByRestaurantResponse_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.rating.poutine.v1.PoutineProto.internal_static_rating_poutine_v1_ListRatingsByRestaurantResponse_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.rating.poutine.v1.ListRatingsByRestaurantResponse.class, com.rating.poutine.v1.ListRatingsByRestaurantResponse.Builder.class);
    }

    // Construct using com.rating.poutine.v1.ListRatingsByRestaurantResponse.newBuilder()
    private Builder() {

    }

    private Builder(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      super(parent);

    }
    @java.lang.Override
    public Builder clear() {
      super.clear();
      bitField0_ = 0;
      if (ratingsBuilder_ == null) {
        ratings_ = java.util.Collections.emptyList();
      } else {
        ratings_ = null;
        ratingsBuilder_.clear();
      }
      bitField0_ = (bitField0_ & ~0x00000001);
      return this;
    }

    @java.lang.Override
    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return com.rating.poutine.v1.PoutineProto.internal_static_rating_poutine_v1_ListRatingsByRestaurantResponse_descriptor;
    }

    @java.lang.Override
    public com.rating.poutine.v1.ListRatingsByRestaurantResponse getDefaultInstanceForType() {
      return com.rating.poutine.v1.ListRatingsByRestaurantResponse.getDefaultInstance();
    }

    @java.lang.Override
    public com.rating.poutine.v1.ListRatingsByRestaurantResponse build() {
      com.rating.poutine.v1.ListRatingsByRestaurantResponse result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    @java.lang.Override
    public com.rating.poutine.v1.ListRatingsByRestaurantResponse buildPartial() {
      com.rating.poutine.v1.ListRatingsByRestaurantResponse result = new com.rating.poutine.v1.ListRatingsByRestaurantResponse(this);
      buildPartialRepeatedFields(result);
      if (bitField0_ != 0) { buildPartial0(result); }
      onBuilt();
      return result;
    }

    private void buildPartialRepeatedFields(com.rating.poutine.v1.ListRatingsByRestaurantResponse result) {
      if (ratingsBuilder_ == null) {
        if (((bitField0_ & 0x00000001) != 0)) {
          ratings_ = java.util.Collections.unmodifiableList(ratings_);
          bitField0_ = (bitField0_ & ~0x00000001);
        }
        result.ratings_ = ratings_;
      } else {
        result.ratings_ = ratingsBuilder_.build();
      }
    }

    private void buildPartial0(com.rating.poutine.v1.ListRatingsByRestaurantResponse result) {
      int from_bitField0_ = bitField0_;
    }

    @java.lang.Override
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof com.rating.poutine.v1.ListRatingsByRestaurantResponse) {
        return mergeFrom((com.rating.poutine.v1.ListRatingsByRestaurantResponse)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(com.rating.poutine.v1.ListRatingsByRestaurantResponse other) {
      if (other == com.rating.poutine.v1.ListRatingsByRestaurantResponse.getDefaultInstance()) return this;
      if (ratingsBuilder_ == null) {
        if (!other.ratings_.isEmpty()) {
          if (ratings_.isEmpty()) {
            ratings_ = other.ratings_;
            bitField0_ = (bitField0_ & ~0x00000001);
          } else {
            ensureRatingsIsMutable();
            ratings_.addAll(other.ratings_);
          }
          onChanged();
        }
      } else {
        if (!other.ratings_.isEmpty()) {
          if (ratingsBuilder_.isEmpty()) {
            ratingsBuilder_.dispose();
            ratingsBuilder_ = null;
            ratings_ = other.ratings_;
            bitField0_ = (bitField0_ & ~0x00000001);
            ratingsBuilder_ = 
              com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders ?
                 internalGetRatingsFieldBuilder() : null;
          } else {
            ratingsBuilder_.addAllMessages(other.ratings_);
          }
        }
      }
      this.mergeUnknownFields(other.getUnknownFields());
      onChanged();
      return this;
    }

    @java.lang.Override
    public final boolean isInitialized() {
      return true;
    }

    @java.lang.Override
    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 10: {
              com.rating.poutine.v1.Poutine m =
                  input.readMessage(
                      com.rating.poutine.v1.Poutine.parser(),
                      extensionRegistry);
              if (ratingsBuilder_ == null) {
                ensureRatingsIsMutable();
                ratings_.add(m);
              } else {
                ratingsBuilder_.addMessage(m);
              }
              break;
            } // case 10
            default: {
              if (!super.parseUnknownField(input, extensionRegistry, tag)) {
                done = true; // was an endgroup tag
              }
              break;
            } // default:
          } // switch (tag)
        } // while (!done)
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.unwrapIOException();
      } finally {
        onChanged();
      } // finally
      return this;
    }
    private int bitField0_;

    private java.util.List<com.rating.poutine.v1.Poutine> ratings_ =
      java.util.Collections.emptyList();
    private void ensureRatingsIsMutable() {
      if (!((bitField0_ & 0x00000001) != 0)) {
        ratings_ = new java.util.ArrayList<com.rating.poutine.v1.Poutine>(ratings_);
        bitField0_ |= 0x00000001;
       }
    }

    private com.google.protobuf.RepeatedFieldBuilder<
        com.rating.poutine.v1.Poutine, com.rating.poutine.v1.Poutine.Builder, com.rating.poutine.v1.PoutineOrBuilder> ratingsBuilder_;

    /**
     * <code>repeated .rating.poutine.v1.Poutine ratings = 1 [json_name = "ratings"];</code>
     */
    public java.util.List<com.rating.poutine.v1.Poutine> getRatingsList() {
      if (ratingsBuilder_ == null) {
        return java.util.Collections.unmodifiableList(ratings_);
      } else {
        return ratingsBuilder_.getMessageList();
      }
    }
    /**
     * <code>repeated .rating.poutine.v1.Poutine ratings = 1 [json_name = "ratings"];</code>
     */
    public int getRatingsCount() {
      if (ratingsBuilder_ == null) {
        return ratings_.size();
      } else {
        return ratingsBuilder_.getCount();
      }
    }
    /**
     * <code>repeated .rating.poutine.v1.Poutine ratings = 1 [json_name = "ratings"];</code>
     */
    public com.rating.poutine.v1.Poutine getRatings(int index) {
      if (ratingsBuilder_ == null) {
        return ratings_.get(index);
      } else {
        return ratingsBuilder_.getMessage(index);
      }
    }
    /**
     * <code>repeated .rating.poutine.v1.Poutine ratings = 1 [json_name = "ratings"];</code>
     */
    public Builder setRatings(
        int index, com.rating.poutine.v1.Poutine value) {
      if (ratingsBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensureRatingsIsMutable();
        ratings_.set(index, value);
        onChanged();
      } else {
        ratingsBuilder_.setMessage(index, value);
      }
      return this;
    }
    /**
     * <code>repeated .rating.poutine.v1.Poutine ratings = 1 [json_name = "ratings"];</code>
     */
    public Builder setRatings(
        int index, com.rating.poutine.v1.Poutine.Builder builderForValue) {
      if (ratingsBuilder_ == null) {
        ensureRatingsIsMutable();
        ratings_.set(index, builderForValue.build());
        onChanged();
      } else {
        ratingsBuilder_.setMessage(index, builderForValue.build());
      }
      return this;
    }
    /**
     * <code>repeated .rating.poutine.v1.Poutine ratings = 1 [json_name = "ratings"];</code>
     */
    public Builder addRatings(com.rating.poutine.v1.Poutine value) {
      if (ratingsBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensureRatingsIsMutable();
        ratings_.add(value);
        onChanged();
      } else {
        ratingsBuilder_.addMessage(value);
      }
      return this;
    }
    /**
     * <code>repeated .rating.poutine.v1.Poutine ratings = 1 [json_name = "ratings"];</code>
     */
    public Builder addRatings(
        int index, com.rating.poutine.v1.Poutine value) {
      if (ratingsBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensureRatingsIsMutable();
        ratings_.add(index, value);
        onChanged();
      } else {
        ratingsBuilder_.addMessage(index, value);
      }
      return this;
    }
    /**
     * <code>repeated .rating.poutine.v1.Poutine ratings = 1 [json_name = "ratings"];</code>
     */
    public Builder addRatings(
        com.rating.poutine.v1.Poutine.Builder builderForValue) {
      if (ratingsBuilder_ == null) {
        ensureRatingsIsMutable();
        ratings_.add(builderForValue.build());
        onChanged();
      } else {
        ratingsBuilder_.addMessage(builderForValue.build());
      }
      return this;
    }
    /**
     * <code>repeated .rating.poutine.v1.Poutine ratings = 1 [json_name = "ratings"];</code>
     */
    public Builder addRatings(
        int index, com.rating.poutine.v1.Poutine.Builder builderForValue) {
      if (ratingsBuilder_ == null) {
        ensureRatingsIsMutable();
        ratings_.add(index, builderForValue.build());
        onChanged();
      } else {
        ratingsBuilder_.addMessage(index, builderForValue.build());
      }
      return this;
    }
    /**
     * <code>repeated .rating.poutine.v1.Poutine ratings = 1 [json_name = "ratings"];</code>
     */
    public Builder addAllRatings(
        java.lang.Iterable<? extends com.rating.poutine.v1.Poutine> values) {
      if (ratingsBuilder_ == null) {
        ensureRatingsIsMutable();
        com.google.protobuf.AbstractMessageLite.Builder.addAll(
            values, ratings_);
        onChanged();
      } else {
        ratingsBuilder_.addAllMessages(values);
      }
      return this;
    }
    /**
     * <code>repeated .rating.poutine.v1.Poutine ratings = 1 [json_name = "ratings"];</code>
     */
    public Builder clearRatings() {
      if (ratingsBuilder_ == null) {
        ratings_ = java.util.Collections.emptyList();
        bitField0_ = (bitField0_ & ~0x00000001);
        onChanged();
      } else {
        ratingsBuilder_.clear();
      }
      return this;
    }
    /**
     * <code>repeated .rating.poutine.v1.Poutine ratings = 1 [json_name = "ratings"];</code>
     */
    public Builder removeRatings(int index) {
      if (ratingsBuilder_ == null) {
        ensureRatingsIsMutable();
        ratings_.remove(index);
        onChanged();
      } else {
        ratingsBuilder_.remove(index);
      }
      return this;
    }
    /**
     * <code>repeated .rating.poutine.v1.Poutine ratings = 1 [json_name = "ratings"];</code>
     */
    public com.rating.poutine.v1.Poutine.Builder getRatingsBuilder(
        int index) {
      return internalGetRatingsFieldBuilder().getBuilder(index);
    }
    /**
     * <code>repeated .rating.poutine.v1.Poutine ratings = 1 [json_name = "ratings"];</code>
     */
    public com.rating.poutine.v1.PoutineOrBuilder getRatingsOrBuilder(
        int index) {
      if (ratingsBuilder_ == null) {
        return ratings_.get(index);  } else {
        return ratingsBuilder_.getMessageOrBuilder(index);
      }
    }
    /**
     * <code>repeated .rating.poutine.v1.Poutine ratings = 1 [json_name = "ratings"];</code>
     */
    public java.util.List<? extends com.rating.poutine.v1.PoutineOrBuilder> 
         getRatingsOrBuilderList() {
      if (ratingsBuilder_ != null) {
        return ratingsBuilder_.getMessageOrBuilderList();
      } else {
        return java.util.Collections.unmodifiableList(ratings_);
      }
    }
    /**
     * <code>repeated .rating.poutine.v1.Poutine ratings = 1 [json_name = "ratings"];</code>
     */
    public com.rating.poutine.v1.Poutine.Builder addRatingsBuilder() {
      return internalGetRatingsFieldBuilder().addBuilder(
          com.rating.poutine.v1.Poutine.getDefaultInstance());
    }
    /**
     * <code>repeated .rating.poutine.v1.Poutine ratings = 1 [json_name = "ratings"];</code>
     */
    public com.rating.poutine.v1.Poutine.Builder addRatingsBuilder(
        int index) {
      return internalGetRatingsFieldBuilder().addBuilder(
          index, com.rating.poutine.v1.Poutine.getDefaultInstance());
    }
    /**
     * <code>repeated .rating.poutine.v1.Poutine ratings = 1 [json_name = "ratings"];</code>
     */
    public java.util.List<com.rating.poutine.v1.Poutine.Builder> 
         getRatingsBuilderList() {
      return internalGetRatingsFieldBuilder().getBuilderList();
    }
    private com.google.protobuf.RepeatedFieldBuilder<
        com.rating.poutine.v1.Poutine, com.rating.poutine.v1.Poutine.Builder, com.rating.poutine.v1.PoutineOrBuilder> 
        internalGetRatingsFieldBuilder() {
      if (ratingsBuilder_ == null) {
        ratingsBuilder_ = new com.google.protobuf.RepeatedFieldBuilder<
            com.rating.poutine.v1.Poutine, com.rating.poutine.v1.Poutine.Builder, com.rating.poutine.v1.PoutineOrBuilder>(
                ratings_,
                ((bitField0_ & 0x00000001) != 0),
                getParentForChildren(),
                isClean());
        ratings_ = null;
      }
      return ratingsBuilder_;
    }

    // @@protoc_insertion_point(builder_scope:rating.poutine.v1.ListRatingsByRestaurantResponse)
  }

  // @@protoc_insertion_point(class_scope:rating.poutine.v1.ListRatingsByRestaurantResponse)
  private static final com.rating.poutine.v1.ListRatingsByRestaurantResponse DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new com.rating.poutine.v1.ListRatingsByRestaurantResponse();
  }

  public static com.rating.poutine.v1.ListRatingsByRestaurantResponse getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<ListRatingsByRestaurantResponse>
      PARSER = new com.google.protobuf.AbstractParser<ListRatingsByRestaurantResponse>() {
    @java.lang.Override
    public ListRatingsByRestaurantResponse parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      Builder builder = newBuilder();
      try {
        builder.mergeFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(builder.buildPartial());
      } catch (com.google.protobuf.UninitializedMessageException e) {
        throw e.asInvalidProtocolBufferException().setUnfinishedMessage(builder.buildPartial());
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(e)
            .setUnfinishedMessage(builder.buildPartial());
      }
      return builder.buildPartial();
    }
  };

  public static com.google.protobuf.Parser<ListRatingsByRestaurantResponse> parser() {
    return PARSER;
  }

  @java.lang.Override
  public com.google.protobuf.Parser<ListRatingsByRestaurantResponse> getParserForType() {
    return PARSER;
  }

  @java.lang.Override
  public com.rating.poutine.v1.ListRatingsByRestaurantResponse getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

