// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: rating/poutine/v1/poutine.proto
// Protobuf Java Version: 4.33.1

package com.rating.poutine.v1;

@com.google.protobuf.Generated
public interface ListRatingsRequestOrBuilder extends
    // @@protoc_insertion_point(interface_extends:rating.poutine.v1.ListRatingsRequest)
    com.google.protobuf.MessageOrBuilder {
}
