// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: rating/poutine/v1/poutine.proto
// Protobuf Java Version: 4.33.1

package com.rating.poutine.v1;

@com.google.protobuf.Generated
public interface ListRatingsByRestaurantRequestOrBuilder extends
    // @@protoc_insertion_point(interface_extends:rating.poutine.v1.ListRatingsByRestaurantRequest)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string restaurant = 1 [json_name = "restaurant"];</code>
   * @return The restaurant.
   */
  java.lang.String getRestaurant();
  /**
   * <code>string restaurant = 1 [json_name = "restaurant"];</code>
   * @return The bytes for restaurant.
   */
  com.google.protobuf.ByteString
      getRestaurantBytes();
}
