// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: rating/poutine/v1/poutine.proto
// Protobuf Java Version: 4.33.1

package com.rating.poutine.v1;

@com.google.protobuf.Generated
public interface ListRatingsResponseOrBuilder extends
    // @@protoc_insertion_point(interface_extends:rating.poutine.v1.ListRatingsResponse)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>repeated .rating.poutine.v1.Poutine ratings = 1 [json_name = "ratings"];</code>
   */
  java.util.List<com.rating.poutine.v1.Poutine> 
      getRatingsList();
  /**
   * <code>repeated .rating.poutine.v1.Poutine ratings = 1 [json_name = "ratings"];</code>
   */
  com.rating.poutine.v1.Poutine getRatings(int index);
  /**
   * <code>repeated .rating.poutine.v1.Poutine ratings = 1 [json_name = "ratings"];</code>
   */
  int getRatingsCount();
  /**
   * <code>repeated .rating.poutine.v1.Poutine ratings = 1 [json_name = "ratings"];</code>
   */
  java.util.List<? extends com.rating.poutine.v1.PoutineOrBuilder> 
      getRatingsOrBuilderList();
  /**
   * <code>repeated .rating.poutine.v1.Poutine ratings = 1 [json_name = "ratings"];</code>
   */
  com.rating.poutine.v1.PoutineOrBuilder getRatingsOrBuilder(
      int index);
}
