// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: rating/poutine/v1/poutine.proto
// Protobuf Java Version: 4.33.1

package com.rating.poutine.v1;

/**
 * Protobuf type {@code rating.poutine.v1.ListRatingsByRestaurantRequest}
 */
@com.google.protobuf.Generated
public final class ListRatingsByRestaurantRequest extends
    com.google.protobuf.GeneratedMessage implements
    // @@protoc_insertion_point(message_implements:rating.poutine.v1.ListRatingsByRestaurantRequest)
    ListRatingsByRestaurantRequestOrBuilder {
private static final long serialVersionUID = 0L;
  static {
    com.google.protobuf.RuntimeVersion.validateProtobufGencodeVersion(
      com.google.protobuf.RuntimeVersion.RuntimeDomain.PUBLIC,
      /* major= */ 4,
      /* minor= */ 33,
      /* patch= */ 1,
      /* suffix= */ "",
      "ListRatingsByRestaurantRequest");
  }
  // Use ListRatingsByRestaurantRequest.newBuilder() to construct.
  private ListRatingsByRestaurantRequest(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
    super(builder);
  }
  private ListRatingsByRestaurantRequest() {
    restaurant_ = "";
  }

  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return com.rating.poutine.v1.PoutineProto.internal_static_rating_poutine_v1_ListRatingsByRestaurantRequest_descriptor;
  }

  @java.lang.Override
  protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internalGetFieldAccessorTable() {
    return com.rating.poutine.v1.PoutineProto.internal_static_rating_poutine_v1_ListRatingsByRestaurantRequest_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            com.rating.poutine.v1.ListRatingsByRestaurantRequest.class, com.rating.poutine.v1.ListRatingsByRestaurantRequest.Builder.class);
  }

  public static final int RESTAURANT_FIELD_NUMBER = 1;
  @SuppressWarnings("serial")
  private volatile java.lang.Object restaurant_ = "";
  /**
   * <code>string restaurant = 1 [json_name = "restaurant"];</code>
   * @return The restaurant.
   */
  @java.lang.Override
  public java.lang.String getRestaurant() {
    java.lang.Object ref = restaurant_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      restaurant_ = s;
      return s;
    }
  }
  /**
   * <code>string restaurant = 1 [json_name = "restaurant"];</code>
   * @return The bytes for restaurant.
   */
  @java.lang.Override
  public com.google.protobuf.ByteString
      getRestaurantBytes() {
    java.lang.Object ref = restaurant_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      restaurant_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  private byte memoizedIsInitialized = -1;
  @java.lang.Override
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  @java.lang.Override
  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    if (!com.google.protobuf.GeneratedMessage.isStringEmpty(restaurant_)) {
      com.google.protobuf.GeneratedMessage.writeString(output, 1, restaurant_);
    }
    getUnknownFields().writeTo(output);
  }

  @java.lang.Override
  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    if (!com.google.protobuf.GeneratedMessage.isStringEmpty(restaurant_)) {
      size += com.google.protobuf.GeneratedMessage.computeStringSize(1, restaurant_);
    }
    size += getUnknownFields().getSerializedSize();
    memoizedSize = size;
    return size;
  }

  @java.lang.Override
  public boolean equals(final java.lang.Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof com.rating.poutine.v1.ListRatingsByRestaurantRequest)) {
      return super.equals(obj);
    }
    com.rating.poutine.v1.ListRatingsByRestaurantRequest other = (com.rating.poutine.v1.ListRatingsByRestaurantRequest) obj;

    if (!getRestaurant()
        .equals(other.getRestaurant())) return false;
    if (!getUnknownFields().equals(other.getUnknownFields())) return false;
    return true;
  }

  @java.lang.Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptor().hashCode();
    hash = (37 * hash) + RESTAURANT_FIELD_NUMBER;
    hash = (53 * hash) + getRestaurant().hashCode();
    hash = (29 * hash) + getUnknownFields().hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static com.rating.poutine.v1.ListRatingsByRestaurantRequest parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.rating.poutine.v1.ListRatingsByRestaurantRequest parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.rating.poutine.v1.ListRatingsByRestaurantRequest parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.rating.poutine.v1.ListRatingsByRestaurantRequest parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.rating.poutine.v1.ListRatingsByRestaurantRequest parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.rating.poutine.v1.ListRatingsByRestaurantRequest parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.rating.poutine.v1.ListRatingsByRestaurantRequest parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseWithIOException(PARSER, input);
  }
  public static com.rating.poutine.v1.ListRatingsByRestaurantRequest parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  public static com.rating.poutine.v1.ListRatingsByRestaurantRequest parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseDelimitedWithIOException(PARSER, input);
  }

  public static com.rating.poutine.v1.ListRatingsByRestaurantRequest parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static com.rating.poutine.v1.ListRatingsByRestaurantRequest parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseWithIOException(PARSER, input);
  }
  public static com.rating.poutine.v1.ListRatingsByRestaurantRequest parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  @java.lang.Override
  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(com.rating.poutine.v1.ListRatingsByRestaurantRequest prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  @java.lang.Override
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @java.lang.Override
  protected Builder newBuilderForType(
      com.google.protobuf.GeneratedMessage.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * Protobuf type {@code rating.poutine.v1.ListRatingsByRestaurantRequest}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessage.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:rating.poutine.v1.ListRatingsByRestaurantRequest)
      com.rating.poutine.v1.ListRatingsByRestaurantRequestOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.rating.poutine.v1.PoutineProto.internal_static_rating_poutine_v1_ListRatingsByRestaurantRequest_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.rating.poutine.v1.PoutineProto.internal_static_rating_poutine_v1_ListRatingsByRestaurantRequest_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.rating.poutine.v1.ListRatingsByRestaurantRequest.class, com.rating.poutine.v1.ListRatingsByRestaurantRequest.Builder.class);
    }

    // Construct using com.rating.poutine.v1.ListRatingsByRestaurantRequest.newBuilder()
    private Builder() {

    }

    private Builder(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      super(parent);

    }
    @java.lang.Override
    public Builder clear() {
      super.clear();
      bitField0_ = 0;
      restaurant_ = "";
      return this;
    }

    @java.lang.Override
    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return com.rating.poutine.v1.PoutineProto.internal_static_rating_poutine_v1_ListRatingsByRestaurantRequest_descriptor;
    }

    @java.lang.Override
    public com.rating.poutine.v1.ListRatingsByRestaurantRequest getDefaultInstanceForType() {
      return com.rating.poutine.v1.ListRatingsByRestaurantRequest.getDefaultInstance();
    }

    @java.lang.Override
    public com.rating.poutine.v1.ListRatingsByRestaurantRequest build() {
      com.rating.poutine.v1.ListRatingsByRestaurantRequest result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    @java.lang.Override
    public com.rating.poutine.v1.ListRatingsByRestaurantRequest buildPartial() {
      com.rating.poutine.v1.ListRatingsByRestaurantRequest result = new com.rating.poutine.v1.ListRatingsByRestaurantRequest(this);
      if (bitField0_ != 0) { buildPartial0(result); }
      onBuilt();
      return result;
    }

    private void buildPartial0(com.rating.poutine.v1.ListRatingsByRestaurantRequest result) {
      int from_bitField0_ = bitField0_;
      if (((from_bitField0_ & 0x00000001) != 0)) {
        result.restaurant_ = restaurant_;
      }
    }

    @java.lang.Override
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof com.rating.poutine.v1.ListRatingsByRestaurantRequest) {
        return mergeFrom((com.rating.poutine.v1.ListRatingsByRestaurantRequest)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(com.rating.poutine.v1.ListRatingsByRestaurantRequest other) {
      if (other == com.rating.poutine.v1.ListRatingsByRestaurantRequest.getDefaultInstance()) return this;
      if (!other.getRestaurant().isEmpty()) {
        restaurant_ = other.restaurant_;
        bitField0_ |= 0x00000001;
        onChanged();
      }
      this.mergeUnknownFields(other.getUnknownFields());
      onChanged();
      return this;
    }

    @java.lang.Override
    public final boolean isInitialized() {
      return true;
    }

    @java.lang.Override
    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 10: {
              restaurant_ = input.readStringRequireUtf8();
              bitField0_ |= 0x00000001;
              break;
            } // case 10
            default: {
              if (!super.parseUnknownField(input, extensionRegistry, tag)) {
                done = true; // was an endgroup tag
              }
              break;
            } // default:
          } // switch (tag)
        } // while (!done)
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.unwrapIOException();
      } finally {
        onChanged();
      } // finally
      return this;
    }
    private int bitField0_;

    private java.lang.Object restaurant_ = "";
    /**
     * <code>string restaurant = 1 [json_name = "restaurant"];</code>
     * @return The restaurant.
     */
    public java.lang.String getRestaurant() {
      java.lang.Object ref = restaurant_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        restaurant_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <code>string restaurant = 1 [json_name = "restaurant"];</code>
     * @return The bytes for restaurant.
     */
    public com.google.protobuf.ByteString
        getRestaurantBytes() {
      java.lang.Object ref = restaurant_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        restaurant_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>string restaurant = 1 [json_name = "restaurant"];</code>
     * @param value The restaurant to set.
     * @return This builder for chaining.
     */
    public Builder setRestaurant(
        java.lang.String value) {
      if (value == null) { throw new NullPointerException(); }
      restaurant_ = value;
      bitField0_ |= 0x00000001;
      onChanged();
      return this;
    }
    /**
     * <code>string restaurant = 1 [json_name = "restaurant"];</code>
     * @return This builder for chaining.
     */
    public Builder clearRestaurant() {
      restaurant_ = getDefaultInstance().getRestaurant();
      bitField0_ = (bitField0_ & ~0x00000001);
      onChanged();
      return this;
    }
    /**
     * <code>string restaurant = 1 [json_name = "restaurant"];</code>
     * @param value The bytes for restaurant to set.
     * @return This builder for chaining.
     */
    public Builder setRestaurantBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) { throw new NullPointerException(); }
      checkByteStringIsUtf8(value);
      restaurant_ = value;
      bitField0_ |= 0x00000001;
      onChanged();
      return this;
    }

    // @@protoc_insertion_point(builder_scope:rating.poutine.v1.ListRatingsByRestaurantRequest)
  }

  // @@protoc_insertion_point(class_scope:rating.poutine.v1.ListRatingsByRestaurantRequest)
  private static final com.rating.poutine.v1.ListRatingsByRestaurantRequest DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new com.rating.poutine.v1.ListRatingsByRestaurantRequest();
  }

  public static com.rating.poutine.v1.ListRatingsByRestaurantRequest getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<ListRatingsByRestaurantRequest>
      PARSER = new com.google.protobuf.AbstractParser<ListRatingsByRestaurantRequest>() {
    @java.lang.Override
    public ListRatingsByRestaurantRequest parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      Builder builder = newBuilder();
      try {
        builder.mergeFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(builder.buildPartial());
      } catch (com.google.protobuf.UninitializedMessageException e) {
        throw e.asInvalidProtocolBufferException().setUnfinishedMessage(builder.buildPartial());
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(e)
            .setUnfinishedMessage(builder.buildPartial());
      }
      return builder.buildPartial();
    }
  };

  public static com.google.protobuf.Parser<ListRatingsByRestaurantRequest> parser() {
    return PARSER;
  }

  @java.lang.Override
  public com.google.protobuf.Parser<ListRatingsByRestaurantRequest> getParserForType() {
    return PARSER;
  }

  @java.lang.Override
  public com.rating.poutine.v1.ListRatingsByRestaurantRequest getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

