// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: rating/poutine/v1/poutine.proto

// Protobuf Java Version: 3.25.3
package com.rating.poutine.v1;

public interface PoutineOrBuilder extends
    // @@protoc_insertion_point(interface_extends:rating.poutine.v1.Poutine)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string restaurant = 1 [json_name = "restaurant"];</code>
   * @return The restaurant.
   */
  java.lang.String getRestaurant();
  /**
   * <code>string restaurant = 1 [json_name = "restaurant"];</code>
   * @return The bytes for restaurant.
   */
  com.google.protobuf.ByteString
      getRestaurantBytes();

  /**
   * <code>uint32 cheese_squeakiness = 2 [json_name = "cheeseSqueakiness"];</code>
   * @return The cheeseSqueakiness.
   */
  int getCheeseSqueakiness();

  /**
   * <code>uint32 gravy_thickness = 3 [json_name = "gravyThickness"];</code>
   * @return The gravyThickness.
   */
  int getGravyThickness();

  /**
   * <code>uint32 fries_crispiness = 4 [json_name = "friesCrispiness"];</code>
   * @return The friesCrispiness.
   */
  int getFriesCrispiness();

  /**
   * <code>string size = 5 [json_name = "size"];</code>
   * @return The size.
   */
  java.lang.String getSize();
  /**
   * <code>string size = 5 [json_name = "size"];</code>
   * @return The bytes for size.
   */
  com.google.protobuf.ByteString
      getSizeBytes();

  /**
   * <code>string comments = 6 [json_name = "comments"];</code>
   * @return The comments.
   */
  java.lang.String getComments();
  /**
   * <code>string comments = 6 [json_name = "comments"];</code>
   * @return The bytes for comments.
   */
  com.google.protobuf.ByteString
      getCommentsBytes();
}
