// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: rating/poutine/v1/poutine.proto

// Protobuf Java Version: 3.25.3
package com.rating.poutine.v1;

public interface PoutineResponseOrBuilder extends
    // @@protoc_insertion_point(interface_extends:rating.poutine.v1.PoutineResponse)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string message = 1 [json_name = "message"];</code>
   * @return The message.
   */
  java.lang.String getMessage();
  /**
   * <code>string message = 1 [json_name = "message"];</code>
   * @return The bytes for message.
   */
  com.google.protobuf.ByteString
      getMessageBytes();

  /**
   * <code>float average_score = 2 [json_name = "averageScore"];</code>
   * @return The averageScore.
   */
  float getAverageScore();
}
