// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: rating/poutine/v1/poutine.proto
// Protobuf Java Version: 4.33.2

package com.rating.poutine.v1;

@com.google.protobuf.Generated
public final class PoutineOuterClass extends com.google.protobuf.GeneratedFile {
  private PoutineOuterClass() {}
  static {
    com.google.protobuf.RuntimeVersion.validateProtobufGencodeVersion(
      com.google.protobuf.RuntimeVersion.RuntimeDomain.PUBLIC,
      /* major= */ 4,
      /* minor= */ 33,
      /* patch= */ 2,
      /* suffix= */ "",
      "PoutineOuterClass");
  }
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_rating_poutine_v1_Poutine_descriptor;
  static final 
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_rating_poutine_v1_Poutine_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_rating_poutine_v1_PoutineRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_rating_poutine_v1_PoutineRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_rating_poutine_v1_PoutineResponse_descriptor;
  static final 
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_rating_poutine_v1_PoutineResponse_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\037rating/poutine/v1/poutine.proto\022\021ratin" +
      "g.poutine.v1\"\334\001\n\007Poutine\022\036\n\nrestaurant\030\001" +
      " \001(\tR\nrestaurant\022-\n\022cheese_squeakiness\030\002" +
      " \001(\rR\021cheeseSqueakiness\022\'\n\017gravy_thickne" +
      "ss\030\003 \001(\rR\016gravyThickness\022)\n\020fries_crispi" +
      "ness\030\004 \001(\rR\017friesCrispiness\022\022\n\004size\030\005 \001(" +
      "\tR\004size\022\032\n\010comments\030\006 \001(\tR\010comments\"F\n\016P" +
      "outineRequest\0224\n\007poutine\030\001 \001(\0132\032.rating." +
      "poutine.v1.PoutineR\007poutine\"P\n\017PoutineRe" +
      "sponse\022\030\n\007message\030\001 \001(\tR\007message\022#\n\raver" +
      "age_score\030\002 \001(\002R\014averageScoreBm\n\025com.rat" +
      "ing.poutine.v1P\001ZRgithub.com/dduzgun-sec" +
      "urity/jug/jug-model/jug-model-go/rating/" +
      "poutine/v1;poutinev1b\006proto3"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        });
    internal_static_rating_poutine_v1_Poutine_descriptor =
      getDescriptor().getMessageType(0);
    internal_static_rating_poutine_v1_Poutine_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_rating_poutine_v1_Poutine_descriptor,
        new java.lang.String[] { "Restaurant", "CheeseSqueakiness", "GravyThickness", "FriesCrispiness", "Size", "Comments", });
    internal_static_rating_poutine_v1_PoutineRequest_descriptor =
      getDescriptor().getMessageType(1);
    internal_static_rating_poutine_v1_PoutineRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_rating_poutine_v1_PoutineRequest_descriptor,
        new java.lang.String[] { "Poutine", });
    internal_static_rating_poutine_v1_PoutineResponse_descriptor =
      getDescriptor().getMessageType(2);
    internal_static_rating_poutine_v1_PoutineResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_rating_poutine_v1_PoutineResponse_descriptor,
        new java.lang.String[] { "Message", "AverageScore", });
    descriptor.resolveAllFeaturesImmutable();
  }

  // @@protoc_insertion_point(outer_class_scope)
}
