// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: rating/poutine/v1/poutine.proto

// Protobuf Java Version: 3.25.3
package com.rating.poutine.v1;

public interface PoutineRequestOrBuilder extends
    // @@protoc_insertion_point(interface_extends:rating.poutine.v1.PoutineRequest)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>.rating.poutine.v1.Poutine poutine = 1 [json_name = "poutine"];</code>
   * @return Whether the poutine field is set.
   */
  boolean hasPoutine();
  /**
   * <code>.rating.poutine.v1.Poutine poutine = 1 [json_name = "poutine"];</code>
   * @return The poutine.
   */
  com.rating.poutine.v1.Poutine getPoutine();
  /**
   * <code>.rating.poutine.v1.Poutine poutine = 1 [json_name = "poutine"];</code>
   */
  com.rating.poutine.v1.PoutineOrBuilder getPoutineOrBuilder();
}
