// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: rating/poutine/v1/poutine.proto

// Protobuf Java Version: 3.25.3
package com.rating.poutine.v1;

public final class PoutineProto {
  private PoutineProto() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_rating_poutine_v1_Poutine_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_rating_poutine_v1_Poutine_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_rating_poutine_v1_PoutineRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_rating_poutine_v1_PoutineRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_rating_poutine_v1_PoutineResponse_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_rating_poutine_v1_PoutineResponse_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\037rating/poutine/v1/poutine.proto\022\021ratin" +
      "g.poutine.v1\032\033buf/validate/validate.prot" +
      "o\"\362\002\n\007Poutine\022+\n\nrestaurant\030\001 \001(\tB\013\272H\010r\003" +
      "\030\200\001\310\001\001R\nrestaurant\022;\n\022cheese_squeakiness" +
      "\030\002 \001(\rB\014\272H\t*\004\030\n(\000\310\001\001R\021cheeseSqueakiness\022" +
      "5\n\017gravy_thickness\030\003 \001(\rB\014\272H\t*\004\030\n(\000\310\001\001R\016" +
      "gravyThickness\0227\n\020fries_crispiness\030\004 \001(\r" +
      "B\014\272H\t*\004\030\n(\000\310\001\001R\017friesCrispiness\022<\n\004size\030" +
      "\005 \001(\tB(\272H%r 2\036^(Small|Medium|Large|X-Lar" +
      "ge)$\310\001\001R\004size\022\'\n\010comments\030\006 \001(\tB\013\272H\010r\003\030\364" +
      "\003\310\001\001R\010comments\022&\n\010location\030\007 \001(\tB\n\272H\007r\002\030" +
      "d\310\001\001R\010location\"F\n\016PoutineRequest\0224\n\007pout" +
      "ine\030\001 \001(\0132\032.rating.poutine.v1.PoutineR\007p" +
      "outine\"P\n\017PoutineResponse\022\030\n\007message\030\001 \001" +
      "(\tR\007message\022#\n\raverage_score\030\002 \001(\002R\014aver" +
      "ageScoreB\337\001\n\025com.rating.poutine.v1B\014Pout" +
      "ineProtoP\001ZRgithub.com/dduzgun-security/" +
      "jug/jug-model/jug-model-go/rating/poutin" +
      "e/v1;poutinev1\242\002\003RPX\252\002\021Rating.Poutine.V1" +
      "\312\002\021Rating\\Poutine\\V1\342\002\035Rating\\Poutine\\V1" +
      "\\GPBMetadata\352\002\023Rating::Poutine::V1b\006prot" +
      "o3"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
          com.buf.validate.ValidateProto.getDescriptor(),
        });
    internal_static_rating_poutine_v1_Poutine_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_rating_poutine_v1_Poutine_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_rating_poutine_v1_Poutine_descriptor,
        new java.lang.String[] { "Restaurant", "CheeseSqueakiness", "GravyThickness", "FriesCrispiness", "Size", "Comments", "Location", });
    internal_static_rating_poutine_v1_PoutineRequest_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_rating_poutine_v1_PoutineRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_rating_poutine_v1_PoutineRequest_descriptor,
        new java.lang.String[] { "Poutine", });
    internal_static_rating_poutine_v1_PoutineResponse_descriptor =
      getDescriptor().getMessageTypes().get(2);
    internal_static_rating_poutine_v1_PoutineResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_rating_poutine_v1_PoutineResponse_descriptor,
        new java.lang.String[] { "Message", "AverageScore", });
    com.google.protobuf.ExtensionRegistry registry =
        com.google.protobuf.ExtensionRegistry.newInstance();
    registry.add(com.buf.validate.ValidateProto.field);
    com.google.protobuf.Descriptors.FileDescriptor
        .internalUpdateFileDescriptor(descriptor, registry);
    com.buf.validate.ValidateProto.getDescriptor();
  }

  // @@protoc_insertion_point(outer_class_scope)
}
