// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: rating/poutine/v1/poutine.proto

// Protobuf Java Version: 3.25.3
package com.rating.poutine.v1;

/**
 * Protobuf type {@code rating.poutine.v1.Poutine}
 */
public final class Poutine extends
    com.google.protobuf.GeneratedMessageV3 implements
    // @@protoc_insertion_point(message_implements:rating.poutine.v1.Poutine)
    PoutineOrBuilder {
private static final long serialVersionUID = 0L;
  // Use Poutine.newBuilder() to construct.
  private Poutine(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
    super(builder);
  }
  private Poutine() {
    restaurant_ = "";
    size_ = "";
    comments_ = "";
    location_ = "";
  }

  @java.lang.Override
  @SuppressWarnings({"unused"})
  protected java.lang.Object newInstance(
      UnusedPrivateParameter unused) {
    return new Poutine();
  }

  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return com.rating.poutine.v1.PoutineProto.internal_static_rating_poutine_v1_Poutine_descriptor;
  }

  @java.lang.Override
  protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internalGetFieldAccessorTable() {
    return com.rating.poutine.v1.PoutineProto.internal_static_rating_poutine_v1_Poutine_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            com.rating.poutine.v1.Poutine.class, com.rating.poutine.v1.Poutine.Builder.class);
  }

  public static final int RESTAURANT_FIELD_NUMBER = 1;
  @SuppressWarnings("serial")
  private volatile java.lang.Object restaurant_ = "";
  /**
   * <code>string restaurant = 1 [json_name = "restaurant", (.buf.validate.field) = { ... }</code>
   * @return The restaurant.
   */
  @java.lang.Override
  public java.lang.String getRestaurant() {
    java.lang.Object ref = restaurant_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      restaurant_ = s;
      return s;
    }
  }
  /**
   * <code>string restaurant = 1 [json_name = "restaurant", (.buf.validate.field) = { ... }</code>
   * @return The bytes for restaurant.
   */
  @java.lang.Override
  public com.google.protobuf.ByteString
      getRestaurantBytes() {
    java.lang.Object ref = restaurant_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      restaurant_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int CHEESE_SQUEAKINESS_FIELD_NUMBER = 2;
  private int cheeseSqueakiness_ = 0;
  /**
   * <code>uint32 cheese_squeakiness = 2 [json_name = "cheeseSqueakiness", (.buf.validate.field) = { ... }</code>
   * @return The cheeseSqueakiness.
   */
  @java.lang.Override
  public int getCheeseSqueakiness() {
    return cheeseSqueakiness_;
  }

  public static final int GRAVY_THICKNESS_FIELD_NUMBER = 3;
  private int gravyThickness_ = 0;
  /**
   * <code>uint32 gravy_thickness = 3 [json_name = "gravyThickness", (.buf.validate.field) = { ... }</code>
   * @return The gravyThickness.
   */
  @java.lang.Override
  public int getGravyThickness() {
    return gravyThickness_;
  }

  public static final int FRIES_CRISPINESS_FIELD_NUMBER = 4;
  private int friesCrispiness_ = 0;
  /**
   * <code>uint32 fries_crispiness = 4 [json_name = "friesCrispiness", (.buf.validate.field) = { ... }</code>
   * @return The friesCrispiness.
   */
  @java.lang.Override
  public int getFriesCrispiness() {
    return friesCrispiness_;
  }

  public static final int SIZE_FIELD_NUMBER = 5;
  @SuppressWarnings("serial")
  private volatile java.lang.Object size_ = "";
  /**
   * <code>string size = 5 [json_name = "size", (.buf.validate.field) = { ... }</code>
   * @return The size.
   */
  @java.lang.Override
  public java.lang.String getSize() {
    java.lang.Object ref = size_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      size_ = s;
      return s;
    }
  }
  /**
   * <code>string size = 5 [json_name = "size", (.buf.validate.field) = { ... }</code>
   * @return The bytes for size.
   */
  @java.lang.Override
  public com.google.protobuf.ByteString
      getSizeBytes() {
    java.lang.Object ref = size_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      size_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int COMMENTS_FIELD_NUMBER = 6;
  @SuppressWarnings("serial")
  private volatile java.lang.Object comments_ = "";
  /**
   * <code>string comments = 6 [json_name = "comments", (.buf.validate.field) = { ... }</code>
   * @return The comments.
   */
  @java.lang.Override
  public java.lang.String getComments() {
    java.lang.Object ref = comments_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      comments_ = s;
      return s;
    }
  }
  /**
   * <code>string comments = 6 [json_name = "comments", (.buf.validate.field) = { ... }</code>
   * @return The bytes for comments.
   */
  @java.lang.Override
  public com.google.protobuf.ByteString
      getCommentsBytes() {
    java.lang.Object ref = comments_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      comments_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int LOCATION_FIELD_NUMBER = 7;
  @SuppressWarnings("serial")
  private volatile java.lang.Object location_ = "";
  /**
   * <code>string location = 7 [json_name = "location", (.buf.validate.field) = { ... }</code>
   * @return The location.
   */
  @java.lang.Override
  public java.lang.String getLocation() {
    java.lang.Object ref = location_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      location_ = s;
      return s;
    }
  }
  /**
   * <code>string location = 7 [json_name = "location", (.buf.validate.field) = { ... }</code>
   * @return The bytes for location.
   */
  @java.lang.Override
  public com.google.protobuf.ByteString
      getLocationBytes() {
    java.lang.Object ref = location_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      location_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  private byte memoizedIsInitialized = -1;
  @java.lang.Override
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  @java.lang.Override
  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(restaurant_)) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 1, restaurant_);
    }
    if (cheeseSqueakiness_ != 0) {
      output.writeUInt32(2, cheeseSqueakiness_);
    }
    if (gravyThickness_ != 0) {
      output.writeUInt32(3, gravyThickness_);
    }
    if (friesCrispiness_ != 0) {
      output.writeUInt32(4, friesCrispiness_);
    }
    if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(size_)) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 5, size_);
    }
    if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(comments_)) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 6, comments_);
    }
    if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(location_)) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 7, location_);
    }
    getUnknownFields().writeTo(output);
  }

  @java.lang.Override
  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(restaurant_)) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(1, restaurant_);
    }
    if (cheeseSqueakiness_ != 0) {
      size += com.google.protobuf.CodedOutputStream
        .computeUInt32Size(2, cheeseSqueakiness_);
    }
    if (gravyThickness_ != 0) {
      size += com.google.protobuf.CodedOutputStream
        .computeUInt32Size(3, gravyThickness_);
    }
    if (friesCrispiness_ != 0) {
      size += com.google.protobuf.CodedOutputStream
        .computeUInt32Size(4, friesCrispiness_);
    }
    if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(size_)) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(5, size_);
    }
    if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(comments_)) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(6, comments_);
    }
    if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(location_)) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(7, location_);
    }
    size += getUnknownFields().getSerializedSize();
    memoizedSize = size;
    return size;
  }

  @java.lang.Override
  public boolean equals(final java.lang.Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof com.rating.poutine.v1.Poutine)) {
      return super.equals(obj);
    }
    com.rating.poutine.v1.Poutine other = (com.rating.poutine.v1.Poutine) obj;

    if (!getRestaurant()
        .equals(other.getRestaurant())) return false;
    if (getCheeseSqueakiness()
        != other.getCheeseSqueakiness()) return false;
    if (getGravyThickness()
        != other.getGravyThickness()) return false;
    if (getFriesCrispiness()
        != other.getFriesCrispiness()) return false;
    if (!getSize()
        .equals(other.getSize())) return false;
    if (!getComments()
        .equals(other.getComments())) return false;
    if (!getLocation()
        .equals(other.getLocation())) return false;
    if (!getUnknownFields().equals(other.getUnknownFields())) return false;
    return true;
  }

  @java.lang.Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptor().hashCode();
    hash = (37 * hash) + RESTAURANT_FIELD_NUMBER;
    hash = (53 * hash) + getRestaurant().hashCode();
    hash = (37 * hash) + CHEESE_SQUEAKINESS_FIELD_NUMBER;
    hash = (53 * hash) + getCheeseSqueakiness();
    hash = (37 * hash) + GRAVY_THICKNESS_FIELD_NUMBER;
    hash = (53 * hash) + getGravyThickness();
    hash = (37 * hash) + FRIES_CRISPINESS_FIELD_NUMBER;
    hash = (53 * hash) + getFriesCrispiness();
    hash = (37 * hash) + SIZE_FIELD_NUMBER;
    hash = (53 * hash) + getSize().hashCode();
    hash = (37 * hash) + COMMENTS_FIELD_NUMBER;
    hash = (53 * hash) + getComments().hashCode();
    hash = (37 * hash) + LOCATION_FIELD_NUMBER;
    hash = (53 * hash) + getLocation().hashCode();
    hash = (29 * hash) + getUnknownFields().hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static com.rating.poutine.v1.Poutine parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.rating.poutine.v1.Poutine parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.rating.poutine.v1.Poutine parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.rating.poutine.v1.Poutine parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.rating.poutine.v1.Poutine parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.rating.poutine.v1.Poutine parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.rating.poutine.v1.Poutine parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static com.rating.poutine.v1.Poutine parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  public static com.rating.poutine.v1.Poutine parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input);
  }

  public static com.rating.poutine.v1.Poutine parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static com.rating.poutine.v1.Poutine parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static com.rating.poutine.v1.Poutine parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  @java.lang.Override
  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(com.rating.poutine.v1.Poutine prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  @java.lang.Override
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @java.lang.Override
  protected Builder newBuilderForType(
      com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * Protobuf type {@code rating.poutine.v1.Poutine}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:rating.poutine.v1.Poutine)
      com.rating.poutine.v1.PoutineOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.rating.poutine.v1.PoutineProto.internal_static_rating_poutine_v1_Poutine_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.rating.poutine.v1.PoutineProto.internal_static_rating_poutine_v1_Poutine_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.rating.poutine.v1.Poutine.class, com.rating.poutine.v1.Poutine.Builder.class);
    }

    // Construct using com.rating.poutine.v1.Poutine.newBuilder()
    private Builder() {

    }

    private Builder(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      super(parent);

    }
    @java.lang.Override
    public Builder clear() {
      super.clear();
      bitField0_ = 0;
      restaurant_ = "";
      cheeseSqueakiness_ = 0;
      gravyThickness_ = 0;
      friesCrispiness_ = 0;
      size_ = "";
      comments_ = "";
      location_ = "";
      return this;
    }

    @java.lang.Override
    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return com.rating.poutine.v1.PoutineProto.internal_static_rating_poutine_v1_Poutine_descriptor;
    }

    @java.lang.Override
    public com.rating.poutine.v1.Poutine getDefaultInstanceForType() {
      return com.rating.poutine.v1.Poutine.getDefaultInstance();
    }

    @java.lang.Override
    public com.rating.poutine.v1.Poutine build() {
      com.rating.poutine.v1.Poutine result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    @java.lang.Override
    public com.rating.poutine.v1.Poutine buildPartial() {
      com.rating.poutine.v1.Poutine result = new com.rating.poutine.v1.Poutine(this);
      if (bitField0_ != 0) { buildPartial0(result); }
      onBuilt();
      return result;
    }

    private void buildPartial0(com.rating.poutine.v1.Poutine result) {
      int from_bitField0_ = bitField0_;
      if (((from_bitField0_ & 0x00000001) != 0)) {
        result.restaurant_ = restaurant_;
      }
      if (((from_bitField0_ & 0x00000002) != 0)) {
        result.cheeseSqueakiness_ = cheeseSqueakiness_;
      }
      if (((from_bitField0_ & 0x00000004) != 0)) {
        result.gravyThickness_ = gravyThickness_;
      }
      if (((from_bitField0_ & 0x00000008) != 0)) {
        result.friesCrispiness_ = friesCrispiness_;
      }
      if (((from_bitField0_ & 0x00000010) != 0)) {
        result.size_ = size_;
      }
      if (((from_bitField0_ & 0x00000020) != 0)) {
        result.comments_ = comments_;
      }
      if (((from_bitField0_ & 0x00000040) != 0)) {
        result.location_ = location_;
      }
    }

    @java.lang.Override
    public Builder clone() {
      return super.clone();
    }
    @java.lang.Override
    public Builder setField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return super.setField(field, value);
    }
    @java.lang.Override
    public Builder clearField(
        com.google.protobuf.Descriptors.FieldDescriptor field) {
      return super.clearField(field);
    }
    @java.lang.Override
    public Builder clearOneof(
        com.google.protobuf.Descriptors.OneofDescriptor oneof) {
      return super.clearOneof(oneof);
    }
    @java.lang.Override
    public Builder setRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        int index, java.lang.Object value) {
      return super.setRepeatedField(field, index, value);
    }
    @java.lang.Override
    public Builder addRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return super.addRepeatedField(field, value);
    }
    @java.lang.Override
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof com.rating.poutine.v1.Poutine) {
        return mergeFrom((com.rating.poutine.v1.Poutine)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(com.rating.poutine.v1.Poutine other) {
      if (other == com.rating.poutine.v1.Poutine.getDefaultInstance()) return this;
      if (!other.getRestaurant().isEmpty()) {
        restaurant_ = other.restaurant_;
        bitField0_ |= 0x00000001;
        onChanged();
      }
      if (other.getCheeseSqueakiness() != 0) {
        setCheeseSqueakiness(other.getCheeseSqueakiness());
      }
      if (other.getGravyThickness() != 0) {
        setGravyThickness(other.getGravyThickness());
      }
      if (other.getFriesCrispiness() != 0) {
        setFriesCrispiness(other.getFriesCrispiness());
      }
      if (!other.getSize().isEmpty()) {
        size_ = other.size_;
        bitField0_ |= 0x00000010;
        onChanged();
      }
      if (!other.getComments().isEmpty()) {
        comments_ = other.comments_;
        bitField0_ |= 0x00000020;
        onChanged();
      }
      if (!other.getLocation().isEmpty()) {
        location_ = other.location_;
        bitField0_ |= 0x00000040;
        onChanged();
      }
      this.mergeUnknownFields(other.getUnknownFields());
      onChanged();
      return this;
    }

    @java.lang.Override
    public final boolean isInitialized() {
      return true;
    }

    @java.lang.Override
    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 10: {
              restaurant_ = input.readStringRequireUtf8();
              bitField0_ |= 0x00000001;
              break;
            } // case 10
            case 16: {
              cheeseSqueakiness_ = input.readUInt32();
              bitField0_ |= 0x00000002;
              break;
            } // case 16
            case 24: {
              gravyThickness_ = input.readUInt32();
              bitField0_ |= 0x00000004;
              break;
            } // case 24
            case 32: {
              friesCrispiness_ = input.readUInt32();
              bitField0_ |= 0x00000008;
              break;
            } // case 32
            case 42: {
              size_ = input.readStringRequireUtf8();
              bitField0_ |= 0x00000010;
              break;
            } // case 42
            case 50: {
              comments_ = input.readStringRequireUtf8();
              bitField0_ |= 0x00000020;
              break;
            } // case 50
            case 58: {
              location_ = input.readStringRequireUtf8();
              bitField0_ |= 0x00000040;
              break;
            } // case 58
            default: {
              if (!super.parseUnknownField(input, extensionRegistry, tag)) {
                done = true; // was an endgroup tag
              }
              break;
            } // default:
          } // switch (tag)
        } // while (!done)
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.unwrapIOException();
      } finally {
        onChanged();
      } // finally
      return this;
    }
    private int bitField0_;

    private java.lang.Object restaurant_ = "";
    /**
     * <code>string restaurant = 1 [json_name = "restaurant", (.buf.validate.field) = { ... }</code>
     * @return The restaurant.
     */
    public java.lang.String getRestaurant() {
      java.lang.Object ref = restaurant_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        restaurant_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <code>string restaurant = 1 [json_name = "restaurant", (.buf.validate.field) = { ... }</code>
     * @return The bytes for restaurant.
     */
    public com.google.protobuf.ByteString
        getRestaurantBytes() {
      java.lang.Object ref = restaurant_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        restaurant_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>string restaurant = 1 [json_name = "restaurant", (.buf.validate.field) = { ... }</code>
     * @param value The restaurant to set.
     * @return This builder for chaining.
     */
    public Builder setRestaurant(
        java.lang.String value) {
      if (value == null) { throw new NullPointerException(); }
      restaurant_ = value;
      bitField0_ |= 0x00000001;
      onChanged();
      return this;
    }
    /**
     * <code>string restaurant = 1 [json_name = "restaurant", (.buf.validate.field) = { ... }</code>
     * @return This builder for chaining.
     */
    public Builder clearRestaurant() {
      restaurant_ = getDefaultInstance().getRestaurant();
      bitField0_ = (bitField0_ & ~0x00000001);
      onChanged();
      return this;
    }
    /**
     * <code>string restaurant = 1 [json_name = "restaurant", (.buf.validate.field) = { ... }</code>
     * @param value The bytes for restaurant to set.
     * @return This builder for chaining.
     */
    public Builder setRestaurantBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) { throw new NullPointerException(); }
      checkByteStringIsUtf8(value);
      restaurant_ = value;
      bitField0_ |= 0x00000001;
      onChanged();
      return this;
    }

    private int cheeseSqueakiness_ ;
    /**
     * <code>uint32 cheese_squeakiness = 2 [json_name = "cheeseSqueakiness", (.buf.validate.field) = { ... }</code>
     * @return The cheeseSqueakiness.
     */
    @java.lang.Override
    public int getCheeseSqueakiness() {
      return cheeseSqueakiness_;
    }
    /**
     * <code>uint32 cheese_squeakiness = 2 [json_name = "cheeseSqueakiness", (.buf.validate.field) = { ... }</code>
     * @param value The cheeseSqueakiness to set.
     * @return This builder for chaining.
     */
    public Builder setCheeseSqueakiness(int value) {

      cheeseSqueakiness_ = value;
      bitField0_ |= 0x00000002;
      onChanged();
      return this;
    }
    /**
     * <code>uint32 cheese_squeakiness = 2 [json_name = "cheeseSqueakiness", (.buf.validate.field) = { ... }</code>
     * @return This builder for chaining.
     */
    public Builder clearCheeseSqueakiness() {
      bitField0_ = (bitField0_ & ~0x00000002);
      cheeseSqueakiness_ = 0;
      onChanged();
      return this;
    }

    private int gravyThickness_ ;
    /**
     * <code>uint32 gravy_thickness = 3 [json_name = "gravyThickness", (.buf.validate.field) = { ... }</code>
     * @return The gravyThickness.
     */
    @java.lang.Override
    public int getGravyThickness() {
      return gravyThickness_;
    }
    /**
     * <code>uint32 gravy_thickness = 3 [json_name = "gravyThickness", (.buf.validate.field) = { ... }</code>
     * @param value The gravyThickness to set.
     * @return This builder for chaining.
     */
    public Builder setGravyThickness(int value) {

      gravyThickness_ = value;
      bitField0_ |= 0x00000004;
      onChanged();
      return this;
    }
    /**
     * <code>uint32 gravy_thickness = 3 [json_name = "gravyThickness", (.buf.validate.field) = { ... }</code>
     * @return This builder for chaining.
     */
    public Builder clearGravyThickness() {
      bitField0_ = (bitField0_ & ~0x00000004);
      gravyThickness_ = 0;
      onChanged();
      return this;
    }

    private int friesCrispiness_ ;
    /**
     * <code>uint32 fries_crispiness = 4 [json_name = "friesCrispiness", (.buf.validate.field) = { ... }</code>
     * @return The friesCrispiness.
     */
    @java.lang.Override
    public int getFriesCrispiness() {
      return friesCrispiness_;
    }
    /**
     * <code>uint32 fries_crispiness = 4 [json_name = "friesCrispiness", (.buf.validate.field) = { ... }</code>
     * @param value The friesCrispiness to set.
     * @return This builder for chaining.
     */
    public Builder setFriesCrispiness(int value) {

      friesCrispiness_ = value;
      bitField0_ |= 0x00000008;
      onChanged();
      return this;
    }
    /**
     * <code>uint32 fries_crispiness = 4 [json_name = "friesCrispiness", (.buf.validate.field) = { ... }</code>
     * @return This builder for chaining.
     */
    public Builder clearFriesCrispiness() {
      bitField0_ = (bitField0_ & ~0x00000008);
      friesCrispiness_ = 0;
      onChanged();
      return this;
    }

    private java.lang.Object size_ = "";
    /**
     * <code>string size = 5 [json_name = "size", (.buf.validate.field) = { ... }</code>
     * @return The size.
     */
    public java.lang.String getSize() {
      java.lang.Object ref = size_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        size_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <code>string size = 5 [json_name = "size", (.buf.validate.field) = { ... }</code>
     * @return The bytes for size.
     */
    public com.google.protobuf.ByteString
        getSizeBytes() {
      java.lang.Object ref = size_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        size_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>string size = 5 [json_name = "size", (.buf.validate.field) = { ... }</code>
     * @param value The size to set.
     * @return This builder for chaining.
     */
    public Builder setSize(
        java.lang.String value) {
      if (value == null) { throw new NullPointerException(); }
      size_ = value;
      bitField0_ |= 0x00000010;
      onChanged();
      return this;
    }
    /**
     * <code>string size = 5 [json_name = "size", (.buf.validate.field) = { ... }</code>
     * @return This builder for chaining.
     */
    public Builder clearSize() {
      size_ = getDefaultInstance().getSize();
      bitField0_ = (bitField0_ & ~0x00000010);
      onChanged();
      return this;
    }
    /**
     * <code>string size = 5 [json_name = "size", (.buf.validate.field) = { ... }</code>
     * @param value The bytes for size to set.
     * @return This builder for chaining.
     */
    public Builder setSizeBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) { throw new NullPointerException(); }
      checkByteStringIsUtf8(value);
      size_ = value;
      bitField0_ |= 0x00000010;
      onChanged();
      return this;
    }

    private java.lang.Object comments_ = "";
    /**
     * <code>string comments = 6 [json_name = "comments", (.buf.validate.field) = { ... }</code>
     * @return The comments.
     */
    public java.lang.String getComments() {
      java.lang.Object ref = comments_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        comments_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <code>string comments = 6 [json_name = "comments", (.buf.validate.field) = { ... }</code>
     * @return The bytes for comments.
     */
    public com.google.protobuf.ByteString
        getCommentsBytes() {
      java.lang.Object ref = comments_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        comments_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>string comments = 6 [json_name = "comments", (.buf.validate.field) = { ... }</code>
     * @param value The comments to set.
     * @return This builder for chaining.
     */
    public Builder setComments(
        java.lang.String value) {
      if (value == null) { throw new NullPointerException(); }
      comments_ = value;
      bitField0_ |= 0x00000020;
      onChanged();
      return this;
    }
    /**
     * <code>string comments = 6 [json_name = "comments", (.buf.validate.field) = { ... }</code>
     * @return This builder for chaining.
     */
    public Builder clearComments() {
      comments_ = getDefaultInstance().getComments();
      bitField0_ = (bitField0_ & ~0x00000020);
      onChanged();
      return this;
    }
    /**
     * <code>string comments = 6 [json_name = "comments", (.buf.validate.field) = { ... }</code>
     * @param value The bytes for comments to set.
     * @return This builder for chaining.
     */
    public Builder setCommentsBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) { throw new NullPointerException(); }
      checkByteStringIsUtf8(value);
      comments_ = value;
      bitField0_ |= 0x00000020;
      onChanged();
      return this;
    }

    private java.lang.Object location_ = "";
    /**
     * <code>string location = 7 [json_name = "location", (.buf.validate.field) = { ... }</code>
     * @return The location.
     */
    public java.lang.String getLocation() {
      java.lang.Object ref = location_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        location_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <code>string location = 7 [json_name = "location", (.buf.validate.field) = { ... }</code>
     * @return The bytes for location.
     */
    public com.google.protobuf.ByteString
        getLocationBytes() {
      java.lang.Object ref = location_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        location_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>string location = 7 [json_name = "location", (.buf.validate.field) = { ... }</code>
     * @param value The location to set.
     * @return This builder for chaining.
     */
    public Builder setLocation(
        java.lang.String value) {
      if (value == null) { throw new NullPointerException(); }
      location_ = value;
      bitField0_ |= 0x00000040;
      onChanged();
      return this;
    }
    /**
     * <code>string location = 7 [json_name = "location", (.buf.validate.field) = { ... }</code>
     * @return This builder for chaining.
     */
    public Builder clearLocation() {
      location_ = getDefaultInstance().getLocation();
      bitField0_ = (bitField0_ & ~0x00000040);
      onChanged();
      return this;
    }
    /**
     * <code>string location = 7 [json_name = "location", (.buf.validate.field) = { ... }</code>
     * @param value The bytes for location to set.
     * @return This builder for chaining.
     */
    public Builder setLocationBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) { throw new NullPointerException(); }
      checkByteStringIsUtf8(value);
      location_ = value;
      bitField0_ |= 0x00000040;
      onChanged();
      return this;
    }
    @java.lang.Override
    public final Builder setUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.setUnknownFields(unknownFields);
    }

    @java.lang.Override
    public final Builder mergeUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.mergeUnknownFields(unknownFields);
    }


    // @@protoc_insertion_point(builder_scope:rating.poutine.v1.Poutine)
  }

  // @@protoc_insertion_point(class_scope:rating.poutine.v1.Poutine)
  private static final com.rating.poutine.v1.Poutine DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new com.rating.poutine.v1.Poutine();
  }

  public static com.rating.poutine.v1.Poutine getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<Poutine>
      PARSER = new com.google.protobuf.AbstractParser<Poutine>() {
    @java.lang.Override
    public Poutine parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      Builder builder = newBuilder();
      try {
        builder.mergeFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(builder.buildPartial());
      } catch (com.google.protobuf.UninitializedMessageException e) {
        throw e.asInvalidProtocolBufferException().setUnfinishedMessage(builder.buildPartial());
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(e)
            .setUnfinishedMessage(builder.buildPartial());
      }
      return builder.buildPartial();
    }
  };

  public static com.google.protobuf.Parser<Poutine> parser() {
    return PARSER;
  }

  @java.lang.Override
  public com.google.protobuf.Parser<Poutine> getParserForType() {
    return PARSER;
  }

  @java.lang.Override
  public com.rating.poutine.v1.Poutine getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

