// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.10
// 	protoc        (unknown)
// source: rating/poutine/v1/poutine.proto

package poutinev1

import (
	_ "buf.build/gen/go/bufbuild/protovalidate/protocolbuffers/go/buf/validate"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Poutine struct {
	state             protoimpl.MessageState `protogen:"open.v1"`
	Restaurant        string                 `protobuf:"bytes,1,opt,name=restaurant,proto3" json:"restaurant,omitempty"`
	CheeseSqueakiness uint32                 `protobuf:"varint,2,opt,name=cheese_squeakiness,json=cheeseSqueakiness,proto3" json:"cheese_squeakiness,omitempty"`
	GravyThickness    uint32                 `protobuf:"varint,3,opt,name=gravy_thickness,json=gravyThickness,proto3" json:"gravy_thickness,omitempty"`
	FriesCrispiness   uint32                 `protobuf:"varint,4,opt,name=fries_crispiness,json=friesCrispiness,proto3" json:"fries_crispiness,omitempty"`
	Size              string                 `protobuf:"bytes,5,opt,name=size,proto3" json:"size,omitempty"`
	Comments          string                 `protobuf:"bytes,6,opt,name=comments,proto3" json:"comments,omitempty"`
	Location          string                 `protobuf:"bytes,7,opt,name=location,proto3" json:"location,omitempty"`
	unknownFields     protoimpl.UnknownFields
	sizeCache         protoimpl.SizeCache
}

func (x *Poutine) Reset() {
	*x = Poutine{}
	mi := &file_rating_poutine_v1_poutine_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Poutine) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Poutine) ProtoMessage() {}

func (x *Poutine) ProtoReflect() protoreflect.Message {
	mi := &file_rating_poutine_v1_poutine_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Poutine.ProtoReflect.Descriptor instead.
func (*Poutine) Descriptor() ([]byte, []int) {
	return file_rating_poutine_v1_poutine_proto_rawDescGZIP(), []int{0}
}

func (x *Poutine) GetRestaurant() string {
	if x != nil {
		return x.Restaurant
	}
	return ""
}

func (x *Poutine) GetCheeseSqueakiness() uint32 {
	if x != nil {
		return x.CheeseSqueakiness
	}
	return 0
}

func (x *Poutine) GetGravyThickness() uint32 {
	if x != nil {
		return x.GravyThickness
	}
	return 0
}

func (x *Poutine) GetFriesCrispiness() uint32 {
	if x != nil {
		return x.FriesCrispiness
	}
	return 0
}

func (x *Poutine) GetSize() string {
	if x != nil {
		return x.Size
	}
	return ""
}

func (x *Poutine) GetComments() string {
	if x != nil {
		return x.Comments
	}
	return ""
}

func (x *Poutine) GetLocation() string {
	if x != nil {
		return x.Location
	}
	return ""
}

type PoutineRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Poutine       *Poutine               `protobuf:"bytes,1,opt,name=poutine,proto3" json:"poutine,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PoutineRequest) Reset() {
	*x = PoutineRequest{}
	mi := &file_rating_poutine_v1_poutine_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PoutineRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PoutineRequest) ProtoMessage() {}

func (x *PoutineRequest) ProtoReflect() protoreflect.Message {
	mi := &file_rating_poutine_v1_poutine_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PoutineRequest.ProtoReflect.Descriptor instead.
func (*PoutineRequest) Descriptor() ([]byte, []int) {
	return file_rating_poutine_v1_poutine_proto_rawDescGZIP(), []int{1}
}

func (x *PoutineRequest) GetPoutine() *Poutine {
	if x != nil {
		return x.Poutine
	}
	return nil
}

type PoutineResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Message       string                 `protobuf:"bytes,1,opt,name=message,proto3" json:"message,omitempty"`
	AverageScore  float32                `protobuf:"fixed32,2,opt,name=average_score,json=averageScore,proto3" json:"average_score,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PoutineResponse) Reset() {
	*x = PoutineResponse{}
	mi := &file_rating_poutine_v1_poutine_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PoutineResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PoutineResponse) ProtoMessage() {}

func (x *PoutineResponse) ProtoReflect() protoreflect.Message {
	mi := &file_rating_poutine_v1_poutine_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PoutineResponse.ProtoReflect.Descriptor instead.
func (*PoutineResponse) Descriptor() ([]byte, []int) {
	return file_rating_poutine_v1_poutine_proto_rawDescGZIP(), []int{2}
}

func (x *PoutineResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *PoutineResponse) GetAverageScore() float32 {
	if x != nil {
		return x.AverageScore
	}
	return 0
}

var File_rating_poutine_v1_poutine_proto protoreflect.FileDescriptor

const file_rating_poutine_v1_poutine_proto_rawDesc = "" +
	"\n" +
	"\x1frating/poutine/v1/poutine.proto\x12\x11rating.poutine.v1\x1a\x1bbuf/validate/validate.proto\"\xf2\x02\n" +
	"\aPoutine\x12+\n" +
	"\n" +
	"restaurant\x18\x01 \x01(\tB\v\xbaH\b\xc8\x01\x01r\x03\x18\x80\x01R\n" +
	"restaurant\x12;\n" +
	"\x12cheese_squeakiness\x18\x02 \x01(\rB\f\xbaH\t\xc8\x01\x01*\x04\x18\n" +
	"(\x00R\x11cheeseSqueakiness\x125\n" +
	"\x0fgravy_thickness\x18\x03 \x01(\rB\f\xbaH\t\xc8\x01\x01*\x04\x18\n" +
	"(\x00R\x0egravyThickness\x127\n" +
	"\x10fries_crispiness\x18\x04 \x01(\rB\f\xbaH\t\xc8\x01\x01*\x04\x18\n" +
	"(\x00R\x0ffriesCrispiness\x12<\n" +
	"\x04size\x18\x05 \x01(\tB(\xbaH%\xc8\x01\x01r 2\x1e^(Small|Medium|Large|X-Large)$R\x04size\x12'\n" +
	"\bcomments\x18\x06 \x01(\tB\v\xbaH\b\xc8\x01\x01r\x03\x18\xf4\x03R\bcomments\x12&\n" +
	"\blocation\x18\a \x01(\tB\n" +
	"\xbaH\a\xc8\x01\x01r\x02\x18dR\blocation\"F\n" +
	"\x0ePoutineRequest\x124\n" +
	"\apoutine\x18\x01 \x01(\v2\x1a.rating.poutine.v1.PoutineR\apoutine\"P\n" +
	"\x0fPoutineResponse\x12\x18\n" +
	"\amessage\x18\x01 \x01(\tR\amessage\x12#\n" +
	"\raverage_score\x18\x02 \x01(\x02R\faverageScoreB\xdf\x01\n" +
	"\x15com.rating.poutine.v1B\fPoutineProtoP\x01ZRgithub.com/dduzgun-security/jug/jug-model/jug-model-go/rating/poutine/v1;poutinev1\xa2\x02\x03RPX\xaa\x02\x11Rating.Poutine.V1\xca\x02\x11Rating\\Poutine\\V1\xe2\x02\x1dRating\\Poutine\\V1\\GPBMetadata\xea\x02\x13Rating::Poutine::V1b\x06proto3"

var (
	file_rating_poutine_v1_poutine_proto_rawDescOnce sync.Once
	file_rating_poutine_v1_poutine_proto_rawDescData []byte
)

func file_rating_poutine_v1_poutine_proto_rawDescGZIP() []byte {
	file_rating_poutine_v1_poutine_proto_rawDescOnce.Do(func() {
		file_rating_poutine_v1_poutine_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_rating_poutine_v1_poutine_proto_rawDesc), len(file_rating_poutine_v1_poutine_proto_rawDesc)))
	})
	return file_rating_poutine_v1_poutine_proto_rawDescData
}

var file_rating_poutine_v1_poutine_proto_msgTypes = make([]protoimpl.MessageInfo, 3)
var file_rating_poutine_v1_poutine_proto_goTypes = []any{
	(*Poutine)(nil),         // 0: rating.poutine.v1.Poutine
	(*PoutineRequest)(nil),  // 1: rating.poutine.v1.PoutineRequest
	(*PoutineResponse)(nil), // 2: rating.poutine.v1.PoutineResponse
}
var file_rating_poutine_v1_poutine_proto_depIdxs = []int32{
	0, // 0: rating.poutine.v1.PoutineRequest.poutine:type_name -> rating.poutine.v1.Poutine
	1, // [1:1] is the sub-list for method output_type
	1, // [1:1] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_rating_poutine_v1_poutine_proto_init() }
func file_rating_poutine_v1_poutine_proto_init() {
	if File_rating_poutine_v1_poutine_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_rating_poutine_v1_poutine_proto_rawDesc), len(file_rating_poutine_v1_poutine_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   3,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_rating_poutine_v1_poutine_proto_goTypes,
		DependencyIndexes: file_rating_poutine_v1_poutine_proto_depIdxs,
		MessageInfos:      file_rating_poutine_v1_poutine_proto_msgTypes,
	}.Build()
	File_rating_poutine_v1_poutine_proto = out.File
	file_rating_poutine_v1_poutine_proto_goTypes = nil
	file_rating_poutine_v1_poutine_proto_depIdxs = nil
}
